.eslintrc.json
.husky/commit-msg
.lintstagedrc.js
.prettierrc
app/layout.tsx
app/page.tsx
app/providers/ReactQueryProvider.tsx
commitlint.config.js
next.config.mjs
panda.config.ts
postcss.config.cjs

1. pnpm 패키지 매니저와 연관 없는 명령어가 존재 (npx)
2. eslintrc.json 파일에서 prettier 관련 플러그인을 넣어줄 때, "prettier" 로 "plugins" 와 "extends" 속성에 각각 넣어줌으로 인해, prettier와 eslint를 동시에 사용할 때 발생할 수 있는 내부적인 이슈를 막지 못함
3. next.config.mjs 파일이 eslint 수행 파일에 포함되어 빨간줄이 뜸
4. 지영님의 건의 -> 세미콜론 필수로 하자!!
1. pnpm 명령어로 통합
2. "plugin:prettier/recommended" 를 extends에 넣어줌으로써 통합
-> 이 때 발생하는 Delete `␍` eslint 오류를 방지하기 위해 eslintrc.json 파일에 prettier 관련 rules 추가
3. ignorePatterns 속성에 next.config.mjs 파일 추가
4. 지영님의 의견 반영 -> 세미콜론 필수입니다 ㅎㅎ

chore: 세팅 내용 일부 변경

---

.github/workflows/review-status-labeling.yml

- PR의 리뷰 진행 상태를 보기 위해서 항상 PR을 클릭해서 확인해보아야 한다.
- GitHub Actions의 workflow에서 PR의 Approved 수를 카운트하여 라벨링을 통해 바로 확인할 수 있도록 하였습니다.
- NA
- NA

feat: approved 상태에 따른 PR의 라벨 추가

---

.github/workflows/deploy-storybook.yml
.storybook/main.ts
.storybook/preview.ts
components/atoms/button/button.stories.tsx
components/atoms/button/button.tsx
components/atoms/button/type.ts
panda.config.ts
postcss.config.cjs

- 공용 button 컴포넌트의 스타일링이 여러 분기라 코드가 복잡함
- storybook 설정 시 pandaCSS 적용이 되지 않음
- 기존에 tab 컴포넌트 때 팀원들이 코드 리뷰를 해주었던 것을 토대로 cx, Map을 사용해 유사한 형태로 리팩토링 진행
- pandaCSS 공식 문서대로 스토리북 적용을 진행 ([참고 링크](https://panda-css.com/docs/installation/storybook)) 
- 
- 위에 참고한 공식 문서 2번째 스텝에서 
`pnpm install -D @pandacss/dev`
`pnpm panda init --postcss`를 하지 않으면 에러가 발생하는 것 같습니다!
- 현재 크로마틱 배포 설정 관련으로 에러가 발생하고 있어서 이 부분은 확인이 필요합니다! @hjy0951 🙇🏻

chore: 공용 button 컴포넌트 작성 및 스토리북 설정을 변경했습니다.

---

components/atoms/button/button.tsx
components/atoms/button/type.ts
components/molecules/tab/tab.tsx

- tab 컴포넌트의 type이 primary와 secondary일 경우, 화면을 꽉 채워주지 않았습니다.
- button 컴포넌트에 외부 스타일을 주입할 수 없었습니다.
- button 태그에 onClick 속성이 부여되지 않았습니다.
- tab 컴포넌트의 base style을 w:'full'로 한 뒤, 정적인 width는 외부에서 부여하는 로직으로 수정하였습니다. type="assistive" 인 경우에만 디폴트로 정적인 값을 유지하였습니다.
- button 컴포넌트의 props에 string 타입의 className prop을 추가하여 외부에서 스타일을 주입할 수 있도록 하였습니다.
- onClick prop을 button 태그에 주입하였습니다.
- 화면을 꽉 채워주지 않는 tab 컴포넌트
- NA

chore: 공통 컴포넌트 일부 수정

---

components/atoms/button/button.tsx
components/atoms/button/type.ts
components/molecules/tab/tab.tsx
features/record/components/molecules/pool-search-result-element.tsx

- useFormContext를 사용하는 파일 내부에 'use client'를 선언해주지 않으면 경고가 발생합니다.
- 컴포넌트 상단에 'use client를 선언해주었습니다.
- NA

fix: useFormContext 관련 경고 해결

---

app/layout.tsx
features/record/components/organisms/form.tsx
features/record/components/organisms/index.ts
features/record/components/organisms/lane-length-bottom-sheet.tsx
features/record/components/organisms/sub-info-text-fields.tsx
features/record/components/organisms/time-bottom-sheet.tsx
features/record/hooks/index.ts
features/record/hooks/use-get-browser-width.tsx
features/record/store/bottom-sheet.ts
features/record/styles/time-picker.css
package.json
pnpm-lock.yaml

- time-picker로 시간을 기록하는 기능을 구현하였습니다.
https://github.com/user-attachments/assets/37d081df-e72e-407b-9fe0-6a95157c25ae
- 시간 내에 완벽히 custom하기에 한계가 있어 최대한 비슷하게 만들어 보았으나 피그마와 완전히 일치하지는 않습니다.
- 시간이 나면 좀 더 수정해 보도록 하겠습니다. api 테스트를 들어가야 해서 우선은 여기까지만 custom 해야할 것 같습니다.

feat: 시간 기록 기능을 구현합니다.

---

apis/fetch-data.ts
app/api/pool/favorite/route.ts
app/api/pool/search/initial/route.ts
components/atoms/icons/star-icon-fill.tsx
components/atoms/icons/star-icon.tsx
features/record/apis/use-toggle-favorite.ts
features/record/components/molecules/pool-search-result-element.tsx
features/record/components/organisms/diary-section.tsx
features/record/components/organisms/pool-search-page-modal.tsx
features/record/components/organisms/pool-search-result-list.tsx

- 수영장 즐겨찾기 기능을 구현하였습니다.
https://github.com/user-attachments/assets/b3e4b9ad-0035-463c-8f0f-1fe3e79406b3
- NA

feat: 수영장 즐겨찾기 기능을 구현합니다.

---

app/google/oauth/index.tsx
app/google/oauth/page.tsx
app/kakao/oauth/index.tsx
app/kakao/oauth/page.tsx

- 소셜 로그인(kakao, google)의 경우 컴포넌트가 아니라 페이지 자체가 클라이언트 사이드 렌더링이 되어야 하기 때문에 아래와 같은 에러가 발생했습니다.
`Error occurred prerendering page "/kakao/oauth". Read more: https://nextjs.org/docs/messages/prerender-error`
- 해당 페이지를 동적 임포트로 불러오고 SSR을 false로 설정했습니다. 
- 앱 라우터는 page.tsx를 디폴트로 보고 있기 때문에 동적 임포트로 불러오는 로그인 페이지를 page.tsx, 기존에 사용하던 로그인 페이지를 index.tsx로 파일명 변경했습니다.
-
-

fix: 소셜 로그인 페이지를 동적 임포트로 불러옵니다.

---

middleware.ts

- 토큰이 없어도 페이지 리다이렉트가 발생하지 않음
- 토큰이 없을 시에 '/login'으로 리다이렉트 하는 로직을 추가합니다.
- 로그인 페이지일 경우 '/' 경로로 이동합니다. 
- 토큰을 받으면 쿠키에 세팅 & 헤더에 설정합니다.
-
-

feat: middleware로 accessToken 재발급 및 리다이렉션

---

middleware.ts

- accessToken 세팅 시 undefined가 뜨는 경우가 있습니다.
- 옵셔널 체이닝을 설정했습니다.
-
-

fix: middleware에서 accessToken 설정 시 옵셔널 체이닝을 적용합니다.

---

app/record-detail/[id]/layout.tsx
app/record-detail/[id]/page.tsx
features/record-detail/components/edit-button.tsx
features/record-detail/sections/detail-description.tsx
features/record-detail/sections/detail-preview.tsx
features/record-detail/types/index.ts
utils/time.ts

- 데이터 타입 변경
- 파도 이미지 렌더링 로직 누락
- 수정 버튼 클릭 시, 기록 페이지로의 이동 필요
- 변경된 데이터에 맞게 공통 함수와 사용하는 방법을 변경했습니다.
- 수영 데이터를 파싱하여 Waves component를 연동합니다.
- 수정 버튼 클릭 시, 해당 메모리 아이디를 쿼리 파라미터로 넣어 보내줍니다.
-

feat: record-detail 페이지 변경된 데이터 반영

---

features/main/calendar/atoms/calendar-item.tsx
features/record/components/organisms/form.tsx
utils/date.ts

- 달력에서 일자를 클릭해도 일자가 바뀌지 않았습니다
- query string을 이용해 날짜를 전달하여 해당 날짜에 수영 기록을 추가할 수 있도록 수정하였습니다.
-

feat: 달력 일자 클릭시 해당 날짜에 기록할 수 있도록 수정

---

features/record-detail/sections/detail-preview.tsx

- item이 string 타입이기 때문에 item.length로 item의 유무를 확인하는 로직에 에러가 발생하였습니다.
- .length를 제거하여 해결했습니다.
- NA
- NA

fix: item 타입에 맞게 item 유무 확인 로직 수정

---

components/molecules/index.ts
components/molecules/record-mark/record-mark.tsx
features/record-detail/sections/detail-description.tsx
features/record-detail/sections/detail-preview.tsx

- 기록 상세 페이지에서 optional data 예외처리가 누락되었습니다.
- RecordMark component의 UI가 detail에서는 달라야 합니다.
- 기록 상세 페이지에 예외처리를 추가합니다
- RecordMark component에 renderType props를 추가하고 스타일을 분기처리합니다.
1. 기록상세
2. 캘린더 화면
-

fix: record-detail 누락된 예외처리 추가 및 RecordMark component 수정

---

app/record/success/page.tsx
components/molecules/page-modal/page-modal.tsx

- page-modal과 기록 성공 페이지 확인 버튼에 max-width 속성이 적용되지 않았습니다.
- page-modal과 기록 성공 페이지 확인 버튼에 max-width를 적용하였습니다.
- NA

fix: page-modal과 기록 성공 페이지 확인 버튼에 max-width 속성 적용

---

features/record/components/organisms/time-bottom-sheet.tsx
features/record/hooks/index.ts
features/record/hooks/use-time-bottom-sheet.tsx
features/record/styles/time-picker.css

- time-picker가 바텀 시트보다 먼저 올라오는 현상이 있었습니다.
- time-picker만을 위한 상태를 하나 추가하여 해결하였습니다.
https://github.com/user-attachments/assets/79167cd2-0dbf-42b0-8ece-7fc334a1365d
- NA

fix: time-picker가 바텀시트보다 먼저 올라오는 현상 수정

---

apis/fetch-data.ts
app/login/login-client.tsx
components/atoms/button/button.stories.tsx
components/atoms/button/button.tsx
middleware.ts

- refreshToken만 존재할 경우 refreshToken을 서버 쪽으로 보내 새로운 accessToken을 발급받아야 합니다. 이때 refreshToken이 유효하지 않는 경우 accessToken이 undefined로도 들어오게 됩니다.
- middleware에 유효하지 않은 refreshToken으로 accessToken을 요청할 경우 분기 처리를 해 login page로 이동하도록 했습니다.
**before (현재 배포환경)**
유효하지 않은 refreshToken으로 accessToken을 재발급 받으니 undefined로 들어옵니다.
https://github.com/user-attachments/assets/a2971037-55dd-4ff7-80e0-9758606103c5
**after (작업 환경)**
refreshToken이 유효하지 않기 때문에 response도 유효하지 않아, /login으로 이동됩니다.
https://github.com/user-attachments/assets/f038a0a6-722d-487f-aa49-1bda70d99fa1
-

fix: accessToken 재발급 시 undefined 생성 건을 수정했습니다.

---

app/record-detail/[id]/page.tsx
components/molecules/dialog/dialog.tsx
features/record-detail/components/cheer-item.tsx
features/record-detail/sections/detail-cheer.tsx
features/record-detail/types/index.ts
hooks/index.ts
hooks/use-drag-scroll.ts

-
- 기록 상세 페이지 내부 응원 조회 영역 마크업 작업입니다.
- PC에서도 드래그가 가능하도록 `useDragScroll` hook을 구현했습니다.
- `slideRef`를 꺼내와 container div에 ref 지정 시, **마우스 이벤트에 따라 해당 영역을 드래그**할 수 있습니다. (PC 대응)
- 터치패드를 사용한 가로 스크롤 기능도 사용할 수 있습니다. (css)
- api 연동을 위한 TODO 주석을 추가했습니다.
1. api 연동
2. 기능 구현
3. 응원하기 바텀 시트를 다른 영역에서도 사용할 수 있게 공통 분리
4. cheer-item component 공통 분리
1. PC
https://github.com/user-attachments/assets/3e0dbd1d-9785-4392-8b3d-ce9f89b59971
5.  MO
https://github.com/user-attachments/assets/c22b4847-df85-4382-8b41-b6c8e3ddeb5d
-

feat: 기록 상세 > 응원 조회 영역 마크업

---

features/record-detail/sections/detail-cheer.tsx
features/record-detail/sections/detail-description.tsx
features/record-detail/sections/detail-diary.tsx

- duration이 분 단위로만 보여지는 이슈를 수정했습니다.
- getFormatDurationTime 함수로 Duration 문자열을 시간,분 단위로 포맷합니다.
-

fix: 기록 상세 페이지 수영 시간 포맷팅 수정

---

features/record/components/organisms/time-bottom-sheet.tsx

- PC 버전에서 time-picker가 왼쪽으로 치우쳐있는 현상이 있었습니다.
- left:0 속성을 제거하였습니다.
- PC
- Mobile
- NA

fix: time-picker가 PC에서 왼쪽으로 치우쳐지는 현상 수정

---

components/molecules/header-bar/header-bar.tsx

- header-bar 컴포넌트에 max-width 속성이 적용되지 않았습니다.
- max-width 속성을 부여하였습니다.
- NA

fix: header-bar 컴포넌트에 max-width 설정

---

hooks/index.ts
hooks/use-bottom-sheet.ts
hooks/use-dialog.ts
hooks/use-modal.ts
hooks/use-prevent-body-scroll.ts

- bottomSheet, dialog, modal 컴포넌트 하단에서 body element의 스크롤 기능이 유지되는 문제가 있습니다.
- body의 스크롤을 제어할 수 있는 `usePreventBodyScroll` hook을 구현합니다.
- bottomSheet, dialog, modal component의 `isOpen` 상태에 따라 스크롤이 막아지도록 훅을 적용합니다.
https://github.com/user-attachments/assets/93c67a65-ab3f-46fa-8b2f-0931ff25b47c
-

feat: usePreventBodyScroll hook 구현 및 적용

---

app/record-detail/[id]/page.tsx
features/record-detail/components/cheer-bottom-sheet.tsx
features/record-detail/components/cheer-modal-item.tsx
features/record-detail/components/cheer-modal.tsx
features/record-detail/components/index.ts
features/record-detail/sections/detail-cheer.tsx
hooks/index.ts
hooks/use-bottom-sheet.ts
hooks/use-dialog.ts
hooks/use-modal.ts
hooks/use-prevent-body-scroll.ts

-
1. 응원하기 모달 내부 요소를 마크업합니다.
-  최대 높이값을 가지며, 내부 요소의 크기에 따라 가변 높이를 가집니다.
-  props, 이벤트 헨들러의 경우 추후 구현 예정입니다.
2. 응원 바텀시트를 별도의 컴포넌트로 분리합니다.
- 분리된 응원 바텀시트 내부에서 추후 API 연동 작업을 거칠 예정입니다. 
- 해당 요소는 다른 페이지에서도 사용될 수 있어, 추후 root component 디렉토리로 이동할 예정입니다.
> props, type 및 데이터 흐름은 API 연동 시에 변경될 수 있습니다.
- PC
- MO
-

feat: 응원하기 모달 마크업 작업 + 응원 바텀시트를 분리합니다.

---

features/record/components/organisms/photo-section.tsx

- 기록 생성 시 PC 모드에서 사진이 틀 밖으로 나오는 현상이 있었습니다.
- 사진 layout에 padding을 고려한 maxWidth를 적용하였습니다.
- NA

fix: 기록 생성 시 PC 모드에서 사진이 틀 밖으로 나오는 현상 수정

---

features/record/components/atoms/select-element.tsx
features/record/components/organisms/distance-page-modal.tsx
features/record/components/organisms/form.tsx
features/record/components/organisms/lane-length-bottom-sheet.tsx
features/record/components/organisms/sub-info-text-fields.tsx
features/record/constants/index.ts
features/record/constants/lane.ts
features/record/hooks/use-distance-page-modal.tsx
features/record/store/form-sub-info.ts

- 수영 거리를 바퀴 수로 입력한 후, lane을 바꾸면 수영 거리가 수정되지 않았습니다.
- 바퀴 수의 수정 상태를 파악하기 위한 상태 하나를 추가한 후, 바퀴 수가 수정된 상태에서 lane이 변경될 시 현재 총 거리를 수정하는 로직을 useEffect 훅으로 구현하였습니다.
- 바퀴 수 입력 후 lane 25m -> 50m로 수정 -> 총 거리 * 2
- 바퀴 수 입력 후 lane 50m -> 25m로 수정 -> 총 거리 / 2
- 총 바퀴 수 입력 후 lane 25m -> 50m로 수정
https://github.com/user-attachments/assets/08eed980-f474-46a6-915c-04cc64d6db0d
- 총 바퀴 수 입력 후 lane 50m -> 25m로 수정
https://github.com/user-attachments/assets/abd7c9ed-5d25-48da-9e3c-5641262056ce
- 영법별 바퀴 수로 입력 후 lane 25m -> 50m로 수정
https://github.com/user-attachments/assets/b8946289-90d0-49e5-b76a-284258c30fc2
- 영법별 바퀴 수로 입력 후 lane 50m -> 25m로 수정
https://github.com/user-attachments/assets/10efbba7-606a-44b5-9afb-bf92ee66a17a
- 미터 수로 입력 후 lane 수정 (총 거리 변화 없음) …

fix: 수영 거리를 바퀴 수로 입력 후, 추후 lane을 수정할 때 총 거리가 수정되지 않는 버그 해결

---

features/profile/components/organisms/profile-edit-form.tsx
features/record/components/atoms/select-element.tsx
features/record/components/organisms/distance-page-modal.tsx
features/record/components/organisms/form.tsx
features/record/components/organisms/lane-length-bottom-sheet.tsx
features/record/components/organisms/sub-info-text-fields.tsx
features/record/constants/index.ts
features/record/constants/lane.ts
features/record/hooks/use-distance-page-modal.tsx
features/record/store/form-sub-info.ts

- 외부에서 totalLaps와 totalMeter를 수영 거리 기록 page-modal에 넘겨주는 부분이 누락되었습니다.
- page-modal에서 assistive tab item 관련 스타일이 깨졌습니다.
- 바퀴 수로 기록 시, 총 거리를 계산하는 로직이 바뀌었습니다(1바퀴 = lane * 2).
- totalLaps와 totalMeter prop을 전달해주었습니다.
- assistive tab의 layout 스타일을 수정하였습니다.
- 계산 로직을 수정하였습니다.
- assistive tab 스타일
- 바퀴 수로 입력 시 1바퀴 당 lane * 2 미터로 계산
https://github.com/user-attachments/assets/b49b7de9-17b3-4e28-b97b-eac1afc49109
- NA

fix: 수영 거리 기록 page-modal에 누락된 props 전달 및 스타일 수정

---

app/record/success/page.tsx
features/record/components/organisms/form.tsx

- 수영 거리 기록 완료 후, 상세 페이지에서 뒤로가기를 누르면 다시 기록 완료 페이지가 나타났습니다.
- replace를 통한 특정 route를 history에 쌓이지 않도록 처리하였습니다.
https://github.com/user-attachments/assets/17402805-aa3a-41ea-ba45-8d74148e0268
- 아이디어를 내준 지영님 감사합니다:)
- Todo: 기록된 달력 날짜 클릭 -> 상세 페이지의 수정 버튼 클릭 -> 기록 페이지에서 기록 수정 완료 후 다시 상세 페이지로 접근 -> 뒤로가기를 두번 눌러야 홈으로 이동되는 로직 처리 필요
- 기록 상세 페이지에서 수정 버튼 클릭 시, 기록 페이지로 넘어갈 때도 replace를 처리하면 해결되지만 / 해당 방식으로 처리하면 홈 -> 기록 상세 페이지 -> 기록 페이지에서 뒤로가기를 누르면 상세 페이지로 이동되는게 아니라 바로 홈으로 이동되게 되어서 이 로직이 괜찮을까 의논이 필요할 것 같습니다.

chore: 수영 거리 기록 로직과 관련된 routing 수정

---

apis/server-cookie.ts

- 사파리에서 로컬 환경일 때 소셜 로그인 진행 시 쿠키가 심기지 않는 이슈가 있었습니다.
- 원칙 상 secure는 https에서만 저장이 되어야 하지만 개발 편의 상 localhost에서는 예외로 취급하는 것으로 알고 있습니다. 
- 하지만 갑자기 진행이 되지 않아 개발 환경인지 프로덕트 환경인지 확인하여 secure 값을 불리언으로 주는 방식으로 수정했습니다. ([참고](https://shanepark.tistory.com/454#google_vignette))
-
-

fix: 사파리에서 로컬 환경일 때 소셜 로그인 진행 시 쿠키가 심기지 않는 버그를 수정했습니다.

---

components/atoms/button/button.stories.tsx
components/atoms/button/button.tsx
components/atoms/button/type.ts

- 버튼 컴포넌트 사용 시, 아이콘은 next/image를 사용하여 src가 string으로 들어가야 하지만 현재 우리 팀은 아이콘을 컴포넌트로 만들고 있어 타입이 일치하지 않습니다.
- 아이콘의 type을 string이 아닌 ReactNode로 수정하고, Button 컴포넌트 내에서도 Image가 아닌 div 태그로 랩핑했습니다.
- 아이콘 사이즈에 대한 스타일링도 기존 스타일링과 유사하게 Map으로 수정하였습니다. 
[페이지에서 사용할 때]
- 스토리북에서는 컴포넌트를 아이콘으로 넣다 보니 테스트할 수 없습니다. (하는 방법을 찾지 못했는데 아신다면 알려주시면 감사하겠습니다!)
- 그래서 스토리를 3가지 따로 만들어두어서 여기서 다른 props로 테스트하실 수 있습니다.

fix: 버튼의 아이콘 props type을 reactNode로 수정했습니다.

---

components/molecules/text-field/select-text-field.tsx

- PC에서 select-text-field의 input에 마우스를 올리면 커서가 입력 모드로 보여졌습니다.
- select-text-field 컴포넌트의 input 태그에 cursor:"pointer" 속성을 적용하였습니다.
- NA

chore: 가록 페이지에서 select-text-field의 cursor를 pointer로 설정

---

features/record/components/organisms/form.tsx

- 기록 페이지에서 끝 시간을 고르는 select-text-field에 label이 있었습니다.
- label을 제거해주었습니다. 추가로 label이 없어 올라가는 text-field의 위치를 marginTop 속성으로 조정해 주었습니다.
- before & after
- NA

fix: 기록 페이지에서 끝 시간 select-text-field의 label 제거

---

app/alarm/page.tsx
app/join/gender/page.tsx
app/join/nickname/page.tsx
app/page.tsx
app/profile/[id]/follow/page.tsx
app/profile/edit/page.tsx
app/record-detail/[id]/page.tsx
app/record/page.tsx
components/molecules/header-bar/header-bar.tsx
components/molecules/header-bar/header-logo-button.tsx
components/molecules/header-bar/index.ts
components/molecules/header-bar/style.ts
features/record/components/organisms/distance-page-modal.tsx
features/record/components/organisms/pool-search-page-modal.tsx

- header-bar 컴포넌트의 왼쪽 구역에 들어갈 아이콘 종류가 생각보다 많았습니다.
- 왼쪽 구역에 들어갈 아이콘을 정해두지 않고, ReactNode 타입의 children 속성으로 외부에서 넣을 수 있도록 하여 자유도를 높였습니다.
- 서버 컴포넌트 내부에서 사용 시 -> children에 들어갈 요소 dynamic import 후 사용
- 클라이언트 컴포넌트 내부에서 사용 시 -> children에 들어갈 요소 일반 import 후 사용
- 외부 스타일 주입 필요 시 className 속성으로 부여
- HeaderBar 컴포넌트 사용중인 모든 페이지에 수정사항 적용하였습니다.
- 오른쪽 요소인 RightContent 에 들어갈 요소들도 서버 컴포넌트 내부에서는 dynamic import 처리 해주면 좋을 것 같아요~!!

chore: header-bar 컴포넌트 left-content도 외부에서 ReactNode 타입으로 주입할 수 있게끔 구현

---

components/atoms/icons/divider-icon.tsx
components/atoms/icons/index.ts
features/main/components/time-line/molecules/time-line-card.tsx
features/main/components/time-line/organisms/time-line.tsx

- 타임라인 사진 표기 및 칼로리 옆 구분자 누락되었습니다.
- 타임라인 월 구분이 제대로 되지 않는 현상 발생하였습니다.
- 빈 타임라인의 경우, 아이콘이 중앙에 오지 않는 현상이 발생하였습니다.
- 구분자 아이콘 컴포는트를 추가하였습니다
- 월 구분을 위해 사용하는 key를 YYYY-MM 형태로 변환하여 사용하도록 하였습니다.
- 타임라인에서 사잔이 있는 경우 표기
- 칼로리 구분자 추가
- 타임라인 월 구분 정상화 및 무한스크롤 정상 동작
https://github.com/user-attachments/assets/431e34c5-8ae9-4e8e-88ad-051393ca61b0
-

fix: 타임라인 QA 이슈 해결 및 누락된 기능 추가

---

app/record-detail/[id]/page.tsx
features/record-detail/components/cheer-progress.tsx
features/record-detail/components/index.ts
features/record-detail/sections/detail-cheer-fab.tsx
features/record-detail/sections/detail-cheer-modal.tsx
features/record-detail/sections/detail-cheer.tsx
features/record-detail/sections/index.ts

-
- cheer progress component의 마크업 및 동작을 구현합니다.
1. 응원하기 버튼을 누르면 노출됩니다
2. 1200ms 기간동안 노출됩니다
3. 300ms 기간동안 fade-out 효과와 함께 사라집니다
TODO
- api 예외처리 구현
- 바텀 시트 / 응원 모달 flow 다른 컴포넌트로 분리
- MO
https://github.com/user-attachments/assets/674446cf-e386-4ccb-940e-e6240e683ddb
- PC
https://github.com/user-attachments/assets/9e24a6bf-f225-4f8f-929b-94ac1d6fa6b5
-

feat: cheer progress 마크업 및 동작을 구현합니다

---

app/page.tsx
components/molecules/header-bar/header-bar-alarm-button.tsx
components/molecules/header-bar/index.ts

- 홈페이지 헤더의 알림 버튼을 누르면 alarm 페이지로 routing 되도록 구현하였습니다.
https://github.com/user-attachments/assets/33554970-b480-47fa-83a4-7b62076c7a84
- NA

feat: 홈페이지에서 알림 버튼 클릭 시 알림 페이지로 이동되도록 구현

---

features/record/apis/use-memory-edit.ts
features/record/components/organisms/form.tsx

- memoryId가 null일 수도 있습니다.
- 훅의 매개변수 타입을 수정해주었습니다.
- useEditMemory훅 mutation의 onSuccess는 editMode 일때만 실행되므로 onSuccess 내부에서는 memoryId가 string 타입임을 단언할 수 있습니다.
- NA
- NA

fix: form 파일에서 발생하는 build-error 수정

---

app/layout.tsx
features/main/components/calendar/atoms/calendar-item.tsx
features/main/components/calendar/molecules/calendar.tsx

-
- 캘린더 아이템 각각에 적용되고 있던 height full 옵션을 제거합니다
- layout css의 height 100vh 가 사파리에서 동작하지 않아 높이 값을 변경합니다
-
-

fix: calendar item에 적용되고 있던 height full 옵션을 제거합니다

---

components/molecules/text-field/text-field.tsx

- number type의 input에서 focus시, default로 화살표 디자인이 나타났습니다.
- 화살표를 삭제하는 css를 추가해주었습니다.
- before & after
- NA

fix: input의 type이 number일 때 자동으로 생기는 화살표 제거

---

app/profile/[id]/page.tsx
features/profile/components/organisms/index.ts
features/profile/components/organisms/my-page.tsx
features/profile/components/organisms/other-page.tsx
features/profile/components/organisms/profile-container.tsx
features/profile/index.ts
features/profile/types/profile.ts

- figma와 다르게 마이페이지 좌우 padding이 들어간 이슈가 있었습니다.
- GNB가 추가되었습니다.
- Tab 을 기준으로 위에만 좌우 padding이 들어가도록 div 태그로 랩핑했습니다.
- 마이페이지 공통 컴포넌트에 GNB를 추가했습니다.
-

fix: 마이페이지 padding 버그 수정 및 GNB를 추가합니다.

---

features/record/components/organisms/form.tsx

- 기록 생성 or 수정하기 버튼을 연타했을 때, api 호출 시도가 계속 일어납니다.
- 이미 클릭을 했다면 추후에 오는 요청은 전부 return 처리하였습니다.
- NA
- NA

fix: 기록 생성 or 수정에서 이미 한번 버튼을 눌렀다면 다시 눌렀을 때 api 요청 막음 처리

---

constants/visualization.ts
features/main/components/time-line/atoms/swim-record-chart.tsx
styles/colors.ts

- 영법별 색상이 잘못 기입되어 있었습니다.
- 피그마에 지정된 색상으로 수정하였습니다. (자유형 - 파랑/ 배영 - 노랑/ 평영 - 초록/  접영 - 빨강)
-
-

fix: 잘못된 영법별 시각화 색상 변경

---

components/molecules/text-field/text-field.tsx

- IOS에서 input type이 number일 경우에도 숫자 키보드가 뜨지 않았습니다.
- input 태그의 속성을 추가해주었습니다.
- NA

chore: ios 에서 type number인 input 작성 시 숫자 키보드가 뜰 수 있게끔 설정

---

features/record/components/organisms/distance-page-modal.tsx

- 수영 거리 페이지 모달에서 버튼에 safe-area 관련 스타일로 설정해 주었습니다.
- NA
- NA

chore: 수영 거리 페이지 모달에서 버튼에 safe-area 설정

---

app/profile/[id]/follow/page.tsx
app/record-detail/[id]/page.tsx
components/molecules/profile-list-item/profile-list-item.tsx
features/follow/apis/use-follower-list.tsx
features/follow/apis/use-following-list.tsx
features/follow/components/follow-virtual-list.tsx
features/follow/components/index.ts
features/follow/sections/follower-section.tsx
features/follow/sections/following-section.tsx
features/follow/sections/index.ts
features/record-detail/apis/use-cheer-list.tsx

-
- 팔로워, 팔로잉 리스트 마크업 및 데이터 연동 작업입니다
-
-

feat: follower, following list 마크업 및 데이터 연동

---

components/molecules/record-mark/record-mark.tsx
features/main/components/calendar/atoms/calendar-item-content.tsx
features/main/hooks/index.ts
features/main/hooks/use-goal.ts
features/record-detail/sections/detail-preview.tsx

-
- useGoal 훅을 통해 goal 정보를 불러와 시각화에 활용하였습니다.
-
-

feat: 유저가 설정한 목표에 맞는 시각화

---

.github/workflows/build-test.yml

- GitHub Actions 중 빌드 테스트 캐싱 파일 이름에 lock 파일 해싱 키가 누락되었습니다.
- 정상적인 파일 이름으로 수정하였습니다.
-
-

chore: 빌드 테스트 캐싱중 해싱 파일 이름 변경

---

features/news/components/organisms/news-list.tsx

- no-floating-promises 에러가 갑자기 발생하였습니다.
- Promise를 다루는 함수 앞에 void를 붙여 해결하였습니다.
-

fix: no-floating-promises lint error 수정

---

components/molecules/global-navigation-bar/global-navigation-bar.tsx
features/profile/components/organisms/my-page.tsx
hooks/apis/use-current-member-info.ts

- GNB 에서 마이 페이지 라우팅을 추가합니다.
- 내 정보를 불러오는 api의 staleTime을 INFINITY로 설정합니다.
https://github.com/user-attachments/assets/f424d55c-b3b2-4e36-8694-338cc9b304da
- NA

feat: gnb에서 마이페이지 라우팅 구현

---

app/page.tsx
app/profile/[id]/page.tsx
app/setting/page.tsx
components/molecules/header-bar/header-bar-setting-button.tsx
components/molecules/header-bar/index.ts

- 헤더바에 setting 아이콘 클릭 시 라우팅이 필요했습니다.
- main header와 profile header에 적용했습니다.
https://github.com/user-attachments/assets/ef14fbae-269b-414a-b334-a743c445ff14
- 영상 찍으면서 알았는데 이거 마이페이지로 갈 때 loadingArea가 또 나오네용... 추후 수정해야겠습니다!!

feat: 헤더바 설정 아이콘 라우팅 추가 및 기존 아이콘 변경했습니다.

---

features/profile/components/organisms/profile-edit-form.tsx
features/profile/types/profile.ts

- introduction의 타입을 옵셔널로 수정 후, trim 함수를 수행하는 과정에서 예외처리를 추가하였습니다.
- NA
- NA

fix: introduction 타입 옵셔널로 수정

---

app/api/withdrawal/route.ts
features/setting/apis/use-delete-account.ts
features/setting/apis/use-post-withdrawal.ts
features/setting/components/organisms/step-2.tsx
features/setting/components/organisms/step-3.tsx
features/setting/index.ts
features/setting/types/delete.ts
features/setting/types/index.ts
features/setting/types/withdrawal.ts

- 탈퇴 기능(ㅠㅠ)이 추가되었습니다.
- 탈퇴 사유를 post 요청으로 보내고 성공했을 때 delete 요청으로 실제 탈퇴까지 이뤄지도록 mutation을 사용했습니다.
https://github.com/user-attachments/assets/4515aa30-e211-45e6-8f79-8db9f8f7e8d5
-

feat: 탈퇴 기능을 구현합니다.

---

app/api/friend/following/summary/route.ts
features/news/components/atoms/following-list-link-button.tsx
features/news/components/molecules/news-item-wrapper.tsx
features/news/components/organisms/news-list.tsx
features/news/hooks/index.ts
features/news/hooks/use-following-summary.ts
features/news/types/index.ts

- 헤더 및 아이템들의 프로필 이미지가 정상적으로 나타나지 않아 
- 소식 페이지 헤더의 팔로잉 목록 이동 버튼에 API를 연결하였습니다.
- 헤더 및 아이템들의 프로필 이미지가 정상적으로 나타날 수 있도록 필드명을 수정하고 css 속성을 추가하여 적용하였습니다.
-

feat: 소식 페이지 헤더중 팔로잉 목록 이동 버튼을 위한 API 추가

---

features/record/apis/use-pull-edit-memory.ts
features/record/components/organisms/form.tsx
features/record/hooks/use-distance-page-modal.tsx

- 전달되지 않은 props가 있었습니다.
- 예를 들어 영법별 기록의 바퀴 수를 4개 입력했던 기록에서 -> 영법별 기록의 미터 수를 3개 입력으로 수정 후 -> 다시 수정 페이지로 접근하여 보면 처음의 바퀴 수 기록이 일부 남아있는 버그가 있었습니다.
- props를 전달해주었습니다
- gcTime을 0으로 설정해주어 캐시된 데이터가 미리 보여짐으로써 useEffect가 두번 실행되는 현상을 수정하였습니다.
- NA
- NA

fix: 수영 거리 기록 버그 수정

---

constants/visualization.ts
features/main/types/calendar.ts

- 바퀴 수로만 총 거리를 입력시 타임라인 카드의 차트가 뜨지 않았습니다.
- `총바퀴` 타입을 추가하였습니다.
-
-

fix: 바퀴 수로 기록시 타임라인 차트가 뜨지 않는 현상 수정

---

components/molecules/cheer/cheer-bottom-sheet.tsx
components/molecules/cheer/cheer-progress.tsx
hooks/use-cheer-bottom-sheet.ts

-
- usePreventScroll 혹을 바텀시트 컴포넌트 > 훅 내부로 옮깁니다
-
-

refactor: use prevent scroll import 위치 변경

---

features/record/components/organisms/form.tsx

- 기록 후, 다음 기록 시 이전 기록의 사진이 그대로 올라가는 현상이 있었습니다.
- 전역 상태로 관리하는 사진 File을 통신 성공 시, reset 해주었습니다.
- NA
- NA

chore: 기록 후 다음 기록 시 이전 기록에 있던 사진이 그대로 올라가는 현상 수정

---

features/setting/components/organisms/setting-calendar.tsx

- 목표 거리 수정시 수정 사항이 반영되지 않는 현상이 발생했습니다.
- 목표 거리 수정시 현재 유저에 대한 정보를 다시 불러오도록 수정하였습니다.
https://github.com/user-attachments/assets/a19bd1f1-6d5b-41ed-a95b-4b2bceb80f4c
-

fix: 목표 거리 수정시 수정 사항이 반영되지 않는 현상 수정

---

features/record/components/organisms/form.tsx

- 기록 수정에서 빈 값으로 필드를 보낼 시, 해당 필드가 빈 값으로 반영되지 않았습니다.
- 백엔드와 토의를 통해 타입을 재정의 하고, undefined로 수정 요청을 보낼 시에도 해당 필드를 빈 값으로 수정해주었습니다.
- NA
- NA

fix: 기록 수정 버그 백엔드와 타입 조정 후 수정

---

features/notification/apis/use-get-notification.tsx
features/notification/components/molecules/cheer-notification.tsx
features/notification/components/molecules/follow-notification.tsx
features/notification/components/organisms/notification-list.tsx
features/record/apis/use-search-pool.ts

- 알림 페이지에서는 데이터의 크기가 무한대로 늘어날 수 있습니다.
- 추후 알림 개수가 많아질 시, 굳이 그려지지 않아도 될 엘리먼트들까지 그려짐으로써 성능적인 측면에서 매우 큰 영향을 받을 수 있습니다.
- Virtuoso를 활용한 리스트 가상화를 통해 불필요한 엘리먼트들을 DOM에서 제거하였습니다.
- before( 알림 개수 33개 기준 )
- after( 알림 개수 33개 기준 )
- NA

refactor: 알림 페이지의 무한스크롤을 Virtuoso로 변경합니다.

---

components/molecules/page-modal/page-modal.css
components/molecules/text-field/form-text-field.tsx
components/molecules/text-field/text-field.tsx
components/molecules/text-field/type.ts
features/record/components/molecules/distance-field-with-badge.tsx
features/record/components/organisms/distance-page-modal.tsx
features/record/components/organisms/sub-info-text-fields.tsx
utils/input/index.ts
utils/input/prevent-characters.ts
utils/input/prevent-minus.ts

- 바퀴 수 입력 시, 아무 단위로나 마음껏 입력이 가능했습니다.
- 소수점으로 입력될 시, 0.5 단위로 변환되게 함으로써 0.5 단위로의 기록 저장만 허용하였습니다.
- 추가로 미터 입력 시에는 소수점 입력을 아예 제한해주었습니다.
예시
- 바퀴 수에 2.3 입력 시
https://github.com/user-attachments/assets/80a7c796-e1ee-41d5-8f68-7cbb53728a7b
- 바퀴 수에 4.1 입력 시
https://github.com/user-attachments/assets/0424e56e-7fab-4ba4-93d1-ee7d69befdf4
- NA

chore: 바퀴 수의 소수점 입력을 0.5단위로 제한합니다.

---

components/molecules/text-field/form-text-field.tsx
components/molecules/text-field/text-field.tsx
components/molecules/text-field/type.ts
features/record/components/molecules/distance-field-with-badge.tsx
features/record/components/organisms/distance-page-modal.tsx
features/record/components/organisms/sub-info-text-fields.tsx
utils/index.ts
utils/input/index.ts
utils/input/prevent-characters.ts
utils/input/prevent-minus.ts

- 심박수 & 페이스 & 칼로리 input / 수영 거리 기록 페이지 모달 input 에 마이너스 입력이 허용되고 있었습니다.
- 수영 거리 기록 페이지 모달 input 에 maxLength가 적용되지 않았습니다.
- 마이너스 기호 입력을 keyDown 이벤트로 방지하였습니다.
- maxLength 속성을 외부에서 넘겨주었습니다(바퀴 수: 세자리까지, 미터 수: 다섯자리 까지)
- NA
- handleInputChange 함수 내부에서 막기를 시도했는데, 마이너스 기호가 정규식으로 제한이 안되는 것 같아 keyDown 이벤트를 활용하였습니다!

chore: 마이너스 기호 입력 방지 및 maxLength 설정

---

features/news/components/atoms/cheer-up-button.tsx

- 소식 페이지에서 응원 이후 페이지 이동이 없으니 기능 오류 같다는 피드백을 받았습니다.
- 응원 이후 해당 기록 상세 페이지로 이동하도록 수정하였습니다.
https://github.com/user-attachments/assets/1bd3b42c-dead-4f07-905f-a43c9e52c7fa
-

feat: 소식페이지에서 응원 이후 해당 기록 상세 페이지로 이동

---

features/record-detail/sections/detail-preview.tsx

- 사용자가 설정한 목표를 달성했음에도 일반 기록처럼 보이던 현상이 발생했습니다.
- 조건문을 수정하여 정상적으로 보이도록 수정하였습니다.
-
-

fix: 기록 상세 페이지에서 목표 달성에도 그라데이션으로 보이지 않는 현상 수정

---

app/record/page.tsx
features/record/components/organisms/form.tsx
features/record/components/organisms/time-bottom-sheet.tsx
features/record/constants/index.ts
features/record/constants/time.ts
features/record/hooks/use-record-form.tsx
features/record/server-actions/index.ts
features/record/server-actions/save-swim-time.ts
features/record/utils/time.ts

-
- 이전 기록 시간을 다음 기록에 반영하는 로직 & 첫 기록 시 시간 바텀 시트를 자동으로 열어주는 로직을 구현하였습니다.
- 이전 기록 시간을 저장 후 나중에 불러오기 위해 next/cookie를 활용하였습니다.
- 첫 기록 시
https://github.com/user-attachments/assets/825f79e6-63c9-40bb-a804-312bb33f6843
- 두번째 이후 기록 시
https://github.com/user-attachments/assets/19c662bc-cbdb-4bf2-9c0c-d8d317881dbb
- NA

feat: 이전 기록 시간을 다음 기록에 반영하는 로직 & 첫 기록 시 시간 바텀 시트를 자동으로 열어주는 로직을 구현합니다.

---

app/api/black/route.ts
app/profile/[id]/page.tsx
components/molecules/dialog/dialog.stories.tsx
features/profile/components/atoms/block-button.tsx
features/profile/components/atoms/index.ts
features/profile/components/molecules/index.ts
features/profile/components/molecules/my-page-header.tsx
features/profile/components/molecules/other-page-header.tsx
features/profile/hooks/index.ts
features/profile/hooks/use-block-dialog-handler.tsx
features/profile/hooks/use-block-member.ts

- 특정 멤버를 차단하는 기능이 추가되었습니다.
- dialog와 toast로 구현합니다.
https://github.com/user-attachments/assets/4a510b6e-c3a6-4353-aa9e-a466b598c65e
다른 유저로 들어가도 dialog에 잘 적용됩니닷!
- 아직 백엔드 배포가 안 되어 있습니다.

feat: 특정 멤버 차단 기능을 구현합니다. 

---

features/record/components/organisms/form.tsx
features/record/components/organisms/lane-length-bottom-sheet.tsx

- 수영 거리가 없는 상태에서 레인 수정시, 수영 거리가 바뀌는 버그가 있습니다.
- totalDistance가 정의되어 있을 시에만, 레인 수정이 반영되도록 수정하였습니다.
- before
https://github.com/user-attachments/assets/1f0502e4-4845-4974-b379-776d18d1b434
- after
https://github.com/user-attachments/assets/80707d35-a84e-41e7-913c-dbf15ea3ac78
- NA

fix: 수영 거리가 없는 상태에서 레인 수정시, 0m 혹은 NaN이 뜨는 버그 수정

---

components/molecules/page-modal/page-modal.tsx
features/record/components/organisms/pool-search-page-modal.tsx

- 수영장 검색 page-modal에서 검색 결과 리스트만 스크롤 되도록 구현해야 했습니다.
- 검색 결과만 스크롤 되도록 서치바 까지 fixed로 설정 후, placeholder dom을 설정해 주었습니다. 
https://github.com/user-attachments/assets/b5f67b2c-248f-4a61-b5da-d640291c2483
- 특정 구역까지 fixed로 설정해놓는게 최선일까는 약간 의문이 드네요..!! 다른 방식이 있다면 커멘트 남겨주세요 :)

fix: 수영장 검색 page-modal에서, 스크롤되는 영역을 수정합니다.

---

features/record/hooks/use-distance-page-modal.tsx

- 영법별 바퀴를 입력 후, 다시 지우면 NaN 으로 변환되는 버그가 있었습니다.
- 해당 사항을 예외처리 해주었습니다.
- NA
- NA

fix: 영법별 바퀴 입력 버그 수정

---

features/record/hooks/use-distance-page-modal.tsx

- 이전 수영 기록 방법에 따라 수영 거리 기록 page-modal의 디폴트 tab index를 분기처리 해주었습니다.
- 총 미터로 입력 시
https://github.com/user-attachments/assets/2fba56aa-fb95-404d-afc9-c7f3c25202ce
- 총 바퀴로 입력 시
https://github.com/user-attachments/assets/0ba8c6ce-9c5a-4fc6-a070-b98619dc60e8
- 영법별 미터로 입력 시
https://github.com/user-attachments/assets/9aea2939-ef55-4be3-9a27-6487ad3c1465
- 영법별 바퀴로 입력 시
https://github.com/user-attachments/assets/7dcfe5ed-28f7-4086-a81d-8447ee3c58f6
- NA

chore: 이전 수영 기록 방법에 따른 디폴트 tab index 분기처리

---

app/record/success/page.tsx
features/record/components/organisms/form.tsx

- 기록 수정 시에는 새로운 성공 페이지로 이동하는 것이 아닌, toast를 띄운 후 -> 기록 상세 페이지로 이동되는 플로우로 수정하였습니다.
https://github.com/user-attachments/assets/e25c5bd2-c7ba-4f56-9bff-e2b91cdeb020
- NA

chore: 기록 수정 플로우 변경

---

features/login/components/organisms/login-screen.tsx

- 애플 로그인 버튼을 연타하면 로그인이 멈추는 현상이 발생합니다.
- 요청이 많이 가서 그런 건지 정확한 원인은 아직 알 수 없으나, 애플 로그인 버튼을 1번 클릭하면 새 창을 열되 disabled 시키는 형태로 방지했습니다. 
**[as is]**
https://github.com/user-attachments/assets/f369fa47-34eb-49c8-be02-ab9987d6f048
**[to be]**
https://github.com/user-attachments/assets/2d07fec4-dbfc-4806-b725-352859480077
-

fix: 애플 로그인 연타를 방지합니다.

---

app/api/apple/oauth/route.ts
features/login/components/organisms/login-screen.tsx
features/login/hook/use-login-fail-dialog-handler.ts

로그인 에러 시 실패를 받아주는 부분이 누락됨
- 연타 방지를 위해 5초 디바운스
- 에러 401, 400의 경우 /login/login-failed=true 이런 param 붙은 채 이동하고, /login에 왔을 때 저런 param 있으면 dialog 띄워줌 
-

fix: 애플 로그인 에러 시 모달 띄웁니다.

---

features/login/components/organisms/login-screen.tsx

chore: 구글 로그인 주석 해제

---

README.md
components/molecules/text-field/select-text-field.tsx
components/molecules/text-field/type.ts
features/record/components/organisms/form.tsx

- 수영 날짜 선택 필드의 화살표를 제거하기 위한 prop을 하나 추가해주었습니다.
- NA

chore: 수영 날짜 선택 필드의 화살표 제거

---

styles/colors.ts

- 총거리 색상이 예전 시안으로 적용되어있습니다.
- 현재 피그마의 시안대로 변경하였습니다.
-
-

fix: 총거리 색상 현재 시안으로 변경

---

features/record/components/organisms/form.tsx
features/record/components/organisms/time-bottom-sheet.tsx

- 첫 기록에서 마지막 시간이 +50분 자동 설정 될 때, 바텀시트에는 반영이 안되는 현상이 있었습니다.
- 반영되도록 로직을 수정하였습니다.
- 첫 기록
https://github.com/user-attachments/assets/42c8c68f-8b4d-4e1a-9054-abb3f1646057
- 첫 기록 이후
https://github.com/user-attachments/assets/8c2c25bb-3d8b-426a-9f86-8e0af90e1892
- 수정
https://github.com/user-attachments/assets/27a94dab-2bd7-4c7c-821d-e7a8c26c1cdf
- NA

fix: 첫 기록 시도 시, 마지막 시간이 +50분 자동 설정될 때 바텀시트에도 반영되도록 수정

---

app/api/notification/read/route.ts
features/notification/apis/use-read-notification.tsx
features/notification/components/molecules/cheer-notification.tsx
features/notification/components/organisms/notification-list.tsx

- NA
- 알림 클릭 시, 쌓여있는 알림들을 모두 읽음 처리로 로직을 변경합니다.
- NA
- NA

chore: 알림 클릭 시, 쌓여있는 알림들을 모두 읽음 처리로 로직 수정

---

features/profile/components/molecules/my-page-header.tsx

-
-
-
- header className의 gap 변경사항이 동작하지 않아 important 사용했어요
- 좋은 방법이 절대 아니라서 inline Style로 Props 전달하는 것이 더 괜찮을까요?

feat: 본인 프로필 페이지 > 친구 찾기 동선 추가

---

features/notification/components/molecules/follow-notification.tsx
features/record/components/organisms/photo-section.tsx

- 간혹 업로드 된 이미지가 깨진다는 QA가 들어왔습니다.
- 업로드 전에 프론트 측에서 진행하는 resizing 과정에서 크기가 너무 딱 맞춰져 있는 게 원인일 수도 있겠다는 생각이 들었습니다. 해당 크기를 좀 더 넉넉히 설정해 주었습니다.
- NA
- NA

chore: 이미지 깨짐 현상 수정을 위한 시도

---

features/notification/components/molecules/follow-notification.tsx
features/profile/components/organisms/profile-container.tsx

- 자기소개가 긴 경우 프로필 사진이 찌그러지는 현상이 있었습니다.
- flexShrink:0을 추가해주었습니다.
- NA

fix: 자기소개가 긴 경우 프로필 사진이 찌그러지는 현상 수정

---

features/main/components/calendar/atoms/calendar-item-layout.tsx
features/main/components/calendar/molecules/calendar-header.tsx

- 일부 기기에서 달력 내 줄바꿈이 일어난다는 QA가 있었습니다.
- wordBreak: 'keep-all' 속성을 적용해주었습니다.
- NA

fix: 달력 내 줄바꿈 방지

---

features/profile/hooks/use-profile-data.tsx

- 팔로우/언팔로우 시 프로필의 숫자가 바로 반영되지 않고, 페이지를 이탈해야만 확인할 수 있습니다.
- fetchProfileData에 staleTime이 infinity로, 캐싱이 되어 있는 게 원인이었습니다.
- 바람직하진 않지만 매 요청을 다시 보내도록 staleTime을 삭제했습니다.
- 해당 부분은 팔로우/언팔로우 시 우선 ui에서 업데이트를 진행하는 낙관적 업데이트로 추후 수정하면 좋을 것 같습니다!
Uploading 화면 기록 2024-11-12 오후 8.52.21.mov…
-

fix: 팔로우/언팔로우 시 데이터 실시간 반영

---

features/profile/components/organisms/profile-edit-form.tsx

- 프로필 편집 시, 변경 사항이 없는 상태로 수정하기 버튼을 클릭할 경우 무한 로딩이 발생하였습니다.
- 현재 서버에 저장된 정보와 변경 사항이 일치하다면 수정하기 버튼을 비활성화하였습니다.
-
-

fix: 프로필 편집 시 변경점이 없다면 버튼 비활성화
