depromeet/Swimie-Web

.husky/commit-msg
.husky/pre-commit
.lintstagedrc.js
commitlint.config.js
package.json
pnpm-lock.yaml

- 코드의 일관성이 없고 충돌이 발생할 가능성이 있음
- 팀 협업의 표준화가 이루어지지 않음
- husky를 사용한 코드 스타일 유지 및 commit message prefix 통일
- prettier로 var -> const 변경
- 사용하지 않는 변수는 lint에서 캐치
- commit message prefix 불일치 시 에러 발생
- 없음

chore: husky 적용

---

.github/workflows/auto-assignees.yml

- `Assignees`를 항상 수동 클릭해서 넣어야한다.
- GitHub Actions workflow를 통해 자동으로 등록되도록 설정하였습니다.
- [참고 link](https://github.com/marketplace/actions/review-assign-action)
- NA
- NA

feat: auto assignees action 추가

---

.github/labeler.yml

- PR의 라벨을 항상 직접 선택해야 한다.
- GitHub Actions의 workflow를 활용하여 자동화를 할 계획입니다!
- NA
- 미리 라벨러 파일을 업로드하여 이후 PR에서 workflow가 통과하는지 확인이 필요합니다

chore: 자동 라벨링을 위한 라벨러 파일 추가

---

.github/workflows/auto-labeling.yml

- PR 생성시 `Labels`을 직접 등록해야 한다.
- GitHub Actions를 활용해 자동으로 `Labels`를 등록한다.
- [참고 Link](https://github.com/jimschubert/labeler-action)
- NA
- NA

feat: 자동 라벨링을 위한 GitHub-Actions workflow 추가

---

.github/labeler.yml
.github/workflows/auto-labeling.yml

- 라벨링시 PR 타입뿐만 아니라, `title`과 `body`에 존재하는 키워드들을 모두 탐색하여 `type`과 일치하는 문자열이 있는 경우, 라벨이 등록되는 현상이 발생하였습니다.
- 정규식에 PR의 Title에서 type만을 읽을 수 있도록 컨벤션에 포함된 `:`를 포함시켰습니다.
- 추가적으로 라벨에 대한 설명이 불필요하다 생각해 주석을 제거하였습니다.
-  NA
- NA

chore: 자동 라벨링 workflow 파일 및 라벨러 수정

---

app/layout.tsx
app/record-detail/layout.tsx
app/record-detail/page.tsx
components/molecules/bottom-sheet/bottom-sheet.tsx
components/molecules/bottom-sheet/sheet-dim.tsx
constants/index.ts
features/record-detail/index.ts
features/record-detail/sections/detail-description.tsx
features/record-detail/sections/detail-diary.tsx
features/record-detail/sections/detail-preview.tsx
features/record-detail/sections/index.ts
panda.config.ts

-
- rootLayout 의 Max-width를 설정합니다 (상수 사용)
- record-detail의 임시 page, layout 파일을 생성합니다.
- main
- record-detail
-

feat: rootLayout setting / record-detail page, layout 파일을 생성합니다

---

app/layout.tsx
components/molecules/index.ts
components/molecules/text-field/text-field-wrapper.tsx
styles/colors.ts

- local font import가 안되어 폰트 적용이 안되었습니다.
- 디자인 시스템중 하나의 색상에 오타가 존재하였습니다.
- 오타 수정 및 Import 추가
-
-

fix: 누락된 font import 추가 및 잘못 기록된 색상 네이밍 수정

---

app/layout.tsx
app/portal-root.tsx
components/molecules/dialog/dialog.tsx
components/molecules/dialog/index.ts
components/molecules/index.ts
hooks/use-dialog.ts
store/dialog.ts
store/index.ts

- 
1. `Dialog` component 상태 관리를 위한 hook, store 파일 추가
2. `Dialog` component 구현
3. `Portal` component를 통한 body tag에 랜딩되도록 구현 (layout > `PortalRoot` 추가)
> component props명이 직관적이어서 따로 description 추가 안했슴니다~
> 참고 ) 쌓임 정책이 없어 우선은 z-index 임시로 넣어놨는데, 요거 정의 한번 하시죠
-
https://github.com/user-attachments/assets/681b0aeb-c5b9-457c-8e53-c4cf27476a00
- 다음과 같이 사용합니다.

feat: Dialog component를 구현합니다

---

components/molecules/header-bar/header-bar.tsx

- 쌓임 규칙에 대한 컨벤션의 부재
- 쌓임 규칙에 맞게 header-bar zIndex를 200으로 수정하였습니다.
- NA
- NA

chore: header-bar 쌓임 규칙 컨벤션에 따른 zIndex 수정

---

app/page.tsx
components/molecules/tab/tab.tsx
features/main/main-tab/index.ts
features/main/main-tab/main-tab.tsx
styles/colors.ts

- NA
- 피그마 메인 페이지 마크업 추가
- 메인 탭 컴포넌트 추가
- line solid 색상 추가
- 탭 컴포넌트 `width` 삭제
- 프로필 부분은 이미지 컴포넌트를 이용해서 새롭게 개편할 예정입니다!

design: 메인 페이지 마크업 추가

---

components/molecules/bottom-sheet/bottom-sheet.stories.tsx
components/molecules/dialog/dialog.stories.tsx
components/molecules/dialog/dialog.tsx

-
- dialog component storybook 파일을 작성합니다.
-

feat: dialog component storybook 파일을 작성합니다

---

components/molecules/bottom-sheet/bottom-sheet.stories.tsx
components/molecules/dialog/dialog.stories.tsx
components/molecules/dialog/dialog.tsx

feat: bottom-sheet component storybook file을 작성합니다

---

components/atoms/button/type.ts
components/molecules/bottom-sheet/bottom-sheet.stories.tsx
components/molecules/bottom-sheet/bottom-sheet.tsx
components/molecules/dialog/dialog.stories.tsx
components/molecules/dialog/dialog.tsx

- bottom-sheet, dialog 컴포넌트의 디자인이 디자인 시스템과 동일하지 않습니다.
- 디자인을 변경합니다.
참고 피그마: https://www.figma.com/design/J24di133Czur4vkjTiwz5I/2%ED%8C%80-Design-System?node-id=18044-8463&t=4HSsoIvEkmAmJwfC-1
- dialog
- bottom-sheet
-

feat: bottom-sheet, dialog 디자인을 변경합니다.

---

apis/fetch-data.ts
app/api/pool/search/initial/route.ts

- fetchData 사용 시 accessToken을 인자로 전달해야 했는데, 이렇게 하면 휴먼 에러 발생 위험이 있었습니다.
- fetchData 내부에서 accessToken을 불러오고 존재할 경우 사용할 수 있도록 수정했습니다.
-
-

feat: accessToken을 fetchData 내부에서 불러옵니다.

---

apis/fetch-data.ts

- fetchData 반환값에 타입이 없습니다.
- 제네릭 타입을 사용했습니다.
-
-

chore: fetchData에 타입을 넣습니다.

---

apis/fetch-data.ts
app/api/pool/search/initial/route.ts

- fetchData에서 headers['Authorization'] = `Bearer ${accessToken}` 작성 시 에러가 발생합니다.
- Bearer를 삭제했습니다.
-
-

fix: bearer를 삭제합니다.

---

components/atoms/accordion/accordion.tsx
components/atoms/accordion/index.ts
components/atoms/index.ts
features/record/components/organisms/diary-section.tsx
features/record/components/organisms/form.tsx
features/record/components/organisms/index.ts
features/record/components/organisms/lane-length-bottom-sheet.tsx
features/record/components/organisms/sub-info-section.tsx
features/record/components/organisms/sub-info-text-fields.tsx
features/record/components/organisms/time-bottom-sheet.tsx
features/record/hooks/index.ts
features/record/hooks/use-get-browser-width.tsx
features/record/hooks/use-sub-info-text-fields.tsx
features/record/store/bottom-sheet.ts
features/record/styles/time-picker.css
package.json
pnpm-lock.yaml

- merge를 했는데 이상하게 time-picker와 상세 기록 부분이 합쳐지지 않았습니다...
- 해당 부분 merge를 위한 PR 다시 올립니다
- NA
- NA

fix: 반영이 안된 부분 merge 하기 위해 PR 다시 올립니다.

---

apis/fetch-data.ts
app/api/pool/favorite/route.ts
app/api/pool/search/initial/route.ts
app/api/pool/search/route.ts
components/atoms/icons/star-icon-fill.tsx
components/atoms/icons/star-icon.tsx
components/molecules/search-bar/search-bar.tsx
features/record/apis/dto/pool-search.ts
features/record/apis/index.ts
features/record/apis/use-search-pool-initial.ts
features/record/apis/use-search-pool.ts
features/record/apis/use-toggle-favorite.ts
features/record/components/molecules/pool-search-result-element.tsx
features/record/components/organisms/pool-search-page-modal.tsx
features/record/components/organisms/pool-search-result-list.tsx
features/record/hooks/index.ts
features/record/hooks/use-pool-search-page-modal.tsx
package.json
pnpm-lock.yaml

- 수영장 검색 관련 기능들을 구현합니다.
https://github.com/user-attachments/assets/f4e9e7d0-3c2f-4e14-b30e-65508f1d8d66
- 무한 스크롤이 적용되어 있습니다.
- Todo: 스켈레톤 컴포넌트 / 검색 결과가 스크롤 되는 영역 지정해주기

feat: 수영장 검색 관련 기능들을 구현합니다.

---

app/record-detail/[id]/page.tsx
features/record-detail/components/date-picker.tsx
features/record-detail/components/swim-description-item.tsx
features/record-detail/components/swim-stats-item.tsx
features/record-detail/components/swim-tool-item.tsx
features/record-detail/index.ts
features/record-detail/sections/detail-description.tsx
features/record-detail/sections/detail-diary.tsx
features/record-detail/sections/detail-preview.tsx
features/record-detail/types/index.ts

-
- 기록 상세 페이지 api를 연동합니다.
- Data를 각 섹션마다 전달하는 것으로 구현했는데, 요 부분 최적화가 필요합니다.
- 사진 데이터 뜨는 것까지 확인하고 코드 정리할게요
- 다이어리 데이터의 줄바꿈이 어떻게 내려오는지 궁금합니다. (필요 시에 insertHtml로 변경할게요)

feat: 기록 상세 페이지 api 연동

---

app/record-detail/[id]/page.tsx
features/record-detail/components/date-picker.tsx
features/record-detail/components/swim-description-item.tsx
features/record-detail/components/swim-stats-item.tsx
features/record-detail/components/swim-tool-item.tsx
features/record-detail/index.ts
features/record-detail/sections/detail-description.tsx
features/record-detail/sections/detail-diary.tsx
features/record-detail/sections/detail-preview.tsx
features/record-detail/types/index.ts
utils/date.ts
utils/index.ts
utils/time.ts

- 서버에서 내려오는 Date, time이 전부 동일한 문자열입니다. 
- date: 23-12-12
- time: 05:05:05
- 문자열을 포맷팅하여 각 객체값을 꺼내와 사용할 수 있는 함수를 구현합니다.
-
-

feat: format date, time 함수를 추가합니다.

---

app/api/google/oauth/route.ts
app/api/kakao/oauth/route.ts

- 서버와 로그인 기능 구현 과정에서 headers에 origin이 없어 401 에러가 발생했습니다.
- origin을 추가했습니다.
- 로컬 환경에서는 로컬로, 프로덕션 환경에서는 프로덕션으로 요청을 보내도록 환경 변수를 수정했습니다.
-
-

feat: 로그인 origin 설정

---

middleware.ts

- 토큰이 없어도 페이지 리다이렉트가 발생하지 않음
- 토큰이 없을 시에 리다이렉트 하는 로직을 추가합니다.
- accessToken 신규 발급건은 윤언니가 이어서 진행!
-
-

feat: middleware redirect 로직 추가

---

constants/visualization.ts
features/main/calendar/molecules/calendar.tsx

-
- 서버에서 내려주는 형식에 맞게 수영 이름을 한글화하였습니다.
-
-

fix: 영법 이름 한글화

---

app/record/success/page.tsx
features/record/apis/dto/index.ts
features/record/apis/dto/memory.ts
features/record/apis/use-memory.ts
features/record/components/molecules/equipment-select-box.tsx
features/record/components/organisms/form.tsx

- 일부 디자인이 수정되었습니다.
- 기록 완료 페이지 디자인을 수정하였습니다.
- form 하단에 100px 만큼의 영역을 생성 / 기록 완료 버튼에 max-width 속성 추가
- 기록 완료 페이지
- form 하단 영역
- 기록 완료 버튼 max-width
- 장비 섹션 max-width 고려
- 우선 버튼 및 장비 아이템에 정적으로 max-width를 부여하여 해결하였습니다.

design: 변경된 디자인 반영

---

app/page.tsx
constants/visualization.ts
features/main/calendar/molecules/calendar.tsx
features/main/time-line/atoms/index.ts
features/main/time-line/atoms/swim-record-chart.tsx
features/main/time-line/atoms/time-line-card.tsx
features/main/time-line/index.ts
features/main/time-line/molecules/index.ts
features/main/time-line/molecules/time-line.tsx
utils/date.ts
utils/index.ts
utils/visualization.ts

design: 타임라인 마크업 추가

---

features/record-detail/components/swim-stats-item.tsx

- 일전에 수정한 타입을 반영하지 않아 빌드 에러가 발생하고 있습니다.
- DetailStrokes > DetailStroke 타입을 수정합니다.
-
-

fix: DetailStroke type 수정

---

app/record-detail/[id]/page.tsx
features/record-detail/sections/detail-preview.tsx

- build error
- client component인 preview section을 dynamic import 방식으로 수정합니다.
-
-

fix: 다이나믹 import로 build error를 수정합니다

---

app/layout.tsx
components/atoms/divider/divider.tsx
features/record/components/organisms/form.tsx

- 하단 버튼 스타일 수정
- divider 색상 변경
- QA를 위해 양옆 border 추가
-
-

fix: border 추가 및 divider 색상 변경

---

app/api/memory/calendar/route.ts
app/page.tsx
features/main/calendar/index.ts
features/main/calendar/molecules/calendar.tsx
features/main/calendar/types/index.ts
hooks/index.ts
hooks/use-calendar-data.ts

feat: 달력 API 연결

---

features/main/calendar/atoms/calendar-item-content.tsx

- 타입의 경로가 수정되었는데, 반영이 되지 않아 빌드시 오류가 발생하였습니다.
- 새로운 경로로 설정하여 해결하였습니다.
-

fix: 변경된 타입 경로 설정

---

features/main/calendar/atoms/calendar-item.tsx
features/record/components/organisms/distance-page-modal.tsx
features/record/components/organisms/pool-search-page-modal.tsx

- 빌드시 여러 문제가 발생하는 것을 확인했습니다.
- 
-

fix: 빌드 에러 수정

---

features/main/calendar/molecules/calendar.tsx
hooks/use-calendar-data.ts

- 캘린더 데이터 변경 시에 화면 깜빡임
- 캘린더 데이터 `placeholder` option 추가 
- 캘린더 데이터 fetching 시에 `loading` component 추가
https://github.com/user-attachments/assets/d5feeb13-bf06-4b6c-a385-159ac9243d56
-

feat: 캘린더 로딩 예외처리 추가

---

components/molecules/header-bar/header-back-button.tsx

- 헤더바의 조건부 코드에 문제가 있었습니다.
- onClickBack 함수가 있을 시 함수를 실행하는 문법으로 고쳐주었고, 삼항연산자를 사용하여 중복 실행을 막았습니다.
- NA
- NA

fix: 헤더바 컴포넌트를 수정합니다.

---

features/main/calendar/atoms/calendar-item-content.tsx
features/main/calendar/types/index.ts

- 달력 API 데이터 양식이 수정되어 물결 마크를 제대로 그리지 못하였습니다.
- API 응답을 토대로 타입을 수정하였습니다.
-
-

fix: 수정된 API 응답 데이터 타입 수정

---

app/kakao/oauth/index.tsx

- 카카오 소셜 로그인과 구글 소셜 로그인 구현 중 변수명을 잘못 기입했습니다. (__)
- 카카오는 KAKAO_CODE, 구글은 GOOGLE_CODE로 수정했습니다.
-
-

fix: 오탈자를 수정했습니다.

---

components/atoms/loading/loading.tsx

- Loading Area를 이미 사용하고 있는 곳에서 에러가 발생합니다,
- props를 optional로 변경합니다
-
-

fix: loading scale props optional 변경

---

app/record/page.tsx

- searchparams 관련 빌드오류가 났습니다.
- Suspense로 감싸서 해결했습니다.
- NA
- NA

fix: searchparams 관련 빌드 에러 해결

---

apis/fetch-data.ts
app/record-detail/[id]/page.tsx
features/record-detail/sections/detail-description.tsx
features/record-detail/sections/detail-diary.tsx
features/record-detail/sections/detail-preview.tsx
features/record-detail/types/index.ts

- 기록 상세 페이지에서의 data optional 처리가 서버와 싱크가 맞지 않습니다.
- swagger를 기반으로 data optional를 추가했습니다.
-
-

feat: record-detail page 데이터 옵셔널 처리

---

components/molecules/record-mark/index.ts
components/molecules/record-mark/record-mark.tsx
features/main/calendar/atoms/calendar-item-content.tsx

- 기록 방법이 물결, 오수완, 목표달성 그라데이션으로 나누어졌습니다.
-`RecordMark` 컴포넌트로 하나로 묶어 분리하였습니다.
-
-

refactor: 여러 기록 인증 방법을 하나의 컴포넌트로 분리(이미지 제외)

---

next.config.mjs

- 기록 상세 페이지 접근 시, 이미지 도메인이 지정되어있지 않아 오류가 났습니다.
- next.config.js의 image에 remotePatterns를 적용했습니다.
- NA

chore: next.config.js의 image에 remotePatterns 적용

---

apis/fetch-data.ts

- fetchData로 api 요청을 보낼 때 accessToken이 만료되면 401 또는 경우에 따라 404(/의 캘린더의 경우 data.data에서 값을 읽지 못함)가 뜨게 됩니다.
- 모든 요청마다 지영님처럼 (fix/login-unauthorize-error 브랜치 참고) 예외처리를 해도 되지만 fetchData에서 response를 401 또는 404로 받았을 경우, 서버로 refreshToken을 전달해 accessToken을 재발급 받아 이전 요청을 다시 수행하게끔 수정했습니다.
https://github.com/user-attachments/assets/965146e7-548c-4f7d-a45d-5cc0ffb6e926
예시로 새로 발급받은 토큰의 유효기간을 3초로 해서 마지막에 사라졌지만 실제로는 1시간을 부여했습니다.
위와 같이 일부러 정상적인 토큰을 훼손하거나 만료되어도 refreshToken이 있다면 정상적으로 요청이 갑니다.
refreshToken이 없다면 middleware 코드를 토대로 /login으로 redirect됩니다.
- 좀 헷갈리는 점이 middleware에서도 유사한 로직이 작성되어 있습니다. 다만 여기는 토큰의 훼손(401, 404와 같은)이 아니라 유무/만료만 따지고 있는데, middleware에서도 fetchData에 작성한 것과 같은 코드로 수정해보려고 했으나 의도한 대로 되지 않았습니다... middleware에서는 구현할 수 없는 건지 잘 모르겠습니다 🥲

feat: fetchData 사용 시 토큰 만료의 경우 재발급 받는 로직을 구현했습니다.

---

app/google/oauth/index.tsx
app/kakao/oauth/index.tsx
app/login/login-client.tsx
components/atoms/button/button.stories.tsx
components/atoms/button/button.tsx
components/atoms/button/type.ts
components/molecules/dialog/dialog.tsx
store/auth.ts
types/authType.ts

- Button 컴포넌트 사용 시 기존 button에 내재되어 있는 type와 스타일링 props인 type의 이름이 중복됩니다.
- 로그인 설정 관련하여 유저의 닉네임을 불러와야 하는 상황이 추가되었습니다. 
- 기존에 사용했던 스타일링 props type의 이름을 buttonType로 수정했습니다.
- 사용해야 하는 type은 reset, submit, button 3가지 union으로 추가했습니다.
- 로그인 설정 관련하여 서버와 논의한대로 jotai를 사용해 전역 상태 관리 / 쿼리 파라미터 추가했습니다.
https://github.com/user-attachments/assets/5f0dbcb3-20be-4fa2-b2b5-80f144437a86
data.data.data.userName입니다.
- Button 컴포넌트, 그 중에서도 기존 type을 쓴 경우는 dialog 밖에 없어 함께 수정했습니다!

feat: Button 컴포넌트 prop 수정 및 로그인 관련 설정을 추가했습니다.

---

app/api/memory/timeline/route.ts
app/page.tsx
components/molecules/infinite-scroller/index.ts
components/molecules/infinite-scroller/infinite-scroller.tsx
features/main/calendar/types/index.ts
features/main/time-line/index.ts
features/main/time-line/molecules/time-line.tsx
features/main/time-line/types/index.ts
hooks/index.ts
hooks/use-intersection-observer.ts
hooks/use-timeline.ts

-
- useIntersectionObsever 훅과 InfiniteScroller 컴포넌트를 이용하여 무한 스크롤을 구현하였습니다.
- React Query의 useInfiniteQuery를 사용하여 무한 스크롤을 이용하여 요청할 수 있도록 구현하였습니다.
- 메인 페이지 프로필 캐릭터의 LCP 최적화를 위해 priority 옵션을 추가하였습니다.
https://github.com/user-attachments/assets/9f1580a9-37e6-416c-a297-a0f6704abcd3
-

feat: 타임라인 API 연결

---

features/main/time-line/atoms/swim-record-chart.tsx
features/main/time-line/atoms/time-line-card.tsx
features/main/time-line/molecules/time-line.tsx

- 타입이 선언된 위치가 바뀌어 빌드 에러가 발생하였습니다.
- 올바른 위치에서 Import 할 수 있도록 수정하였습니다.
-

fix: 타임라인 빌드 에러 수정

---

app/google/oauth/index.tsx
app/kakao/oauth/index.tsx
store/auth.ts
types/authType.ts

- 서버와 논의하에 user 관련 데이터 중 name을 nickname으로 변경하였습니다.
- 로그인 시, 전역 상태 관리 시 사용하는 name을 nickname으로 수정했습니다.
-
-

fix: user 관련 변수명을 수정합니다.

---

app/record-detail/[id]/layout.tsx
app/record-detail/[id]/page.tsx

-
- header에 누락된 member.name을 부여합니다
-
-

fix: header에 member name을 부여합니다

---

features/main/calendar/molecules/calendar.tsx
features/main/time-line/molecules/time-line.tsx
hooks/use-calendar-data.ts
hooks/use-timeline.ts

- 간헐적으로 발생하는 데이터 undefined 문제
- 예외 처리를 통해 해결
- 스타일 코드 분리
- 타임라인, 달력 데이터 조회 쿼리키에 유저 이름. ㅜ가
-

refactor: 메인페이지 스타일 코드 분리, 데이터 예외 처리, 데이터 조회 쿼리키 추가

---

app/api/image/edit/[memoryId]/route.ts
app/api/memory/edit/[memoryId]/route.ts
app/record/success/page.tsx
features/record/apis/index.ts
features/record/apis/use-image-edit.ts
features/record/apis/use-memory-edit.ts
features/record/components/organisms/form.tsx
features/record/components/organisms/photo-section.tsx

- 기록 수정에서 사진 이미지를 교체했을 때 / 사진 이미지는 교체하지 않았을 때 상황을 분기처리 하여 api를 연결하였습니다.
- 이미지는 수정하지 않았을 때
https://github.com/user-attachments/assets/93858504-5ed1-425f-a7b1-cd96c3325dbe
- 이미지도 수정했을 때
https://github.com/user-attachments/assets/453792b5-98fa-4bac-9eeb-ad704f456a88
- NA

feat: 각 상황별로 수영 기록 수정하는 api 연결

---

app/record-detail/[id]/layout.tsx
app/record-detail/[id]/page.tsx
components/molecules/bottom-sheet/bottom-sheet.tsx
features/record-detail/components/cheer-item.tsx
features/record-detail/components/index.ts
features/record-detail/sections/detail-cheer.tsx
features/record-detail/sections/index.ts

-
- 응원하기 버튼, 바텀시트 영역 마크업 작업입니다.
- 응원하기 버튼, 바텀시트, 헤더의 수정 버튼은 '타인의 기록 상세 페이지'에서만 보여지기 때문에 이 부분 분기처리 예정입니다.
- 동작 관련해서는 미구현 상태입니다.
- PC
https://github.com/user-attachments/assets/7d359058-127a-4197-8b0d-e0fb17676f38
- MO
https://github.com/user-attachments/assets/1abbc29d-846b-4e3d-b9ed-f74084d36cb2
-

feat: 기록 상세 페이지 응원하기 버튼, 바텀시트 마크업

---

app/page.tsx
components/atoms/waves/waves.tsx
features/main/calendar/index.ts
features/main/calendar/molecules/calendar.tsx
features/main/calendar/organisms/index.ts
features/main/calendar/organisms/user-calendar-profile.tsx
hooks/use-calendar-data.ts
store/calendar.ts

- 유저의 수영 횟수, 유저의 이름이 보이지 않음
- 물결 컴포넌트 계산시 NaN 발생
- 달력 + 유저 프로필을 컴포넌트로 분리
- 전역으로 사용중인 유저 이름을 보여주도록 설정
- 데이터 페칭시 총 카운트가 몇개인지 확인 후 전역으로 저장하여 보여주도록 설정
- 물결 컴포넌트에 undefined로 들어오는 너비와 높이 예외 처리
- 유저의 이름이 계속 유지될 수 있도록, 로그인 확인 후 전역 상태로 관리하는 로직이 필요

feat: 메인페이지 달력 위 유저 정보 프로필 추가

---

features/record/components/organisms/form.tsx

- form data를 가공하는 함수에서 빌드 에러가 발생하였습니다.
- isNaN 함수에 타입 단언을 추가해 주었습니다.
- NA

fix: 빌드 에러 해결 

---

app/login/login-client.tsx

- 구글 소셜 로그인 중 인가 code가 배포 환경에서 null로 읽히고 있습니다.
- 파라미터가 최초 동의 이후에는 refresh Token을 받아오지 못하는 것으로 설정된 것 같아 디버깅 중입니다.
-
-

fix: 구글 소셜 로그인을 디버깅합니다.

---

components/molecules/tab/tab.tsx

- 피그마와 다르게 공통 컴포넌트에서 좌우 padding 20px이 누락되었습니다.
- Tab 컴포넌트에 좌우 padding 20px을 추가했습니다.
before
after
- 제보해주신 지영님 감사합니다 (__)

fix: 공통 컴포넌트 Tab의 스타일링을 수정합니다.

---

components/atoms/icons/index.ts
components/molecules/index.ts
components/molecules/record-mark/record-mark.tsx
constants/visualization.ts
features/main/calendar/types/index.ts
features/main/time-line/atoms/card-wrapper.tsx
features/main/time-line/atoms/index.ts
features/main/time-line/atoms/swim-record-chart.tsx
features/main/time-line/index.ts
features/main/time-line/molecules/index.ts
features/main/time-line/molecules/time-line-card.tsx
features/main/time-line/organisms/index.ts
features/main/time-line/organisms/time-line.tsx
features/main/time-line/types/index.ts
hooks/index.ts
utils/date.ts
utils/index.ts
utils/number.ts

-
- 소식 페이지에서 재활용을 위해 타임라인 카드 wrapper를 구현하여 디자인을 추가했습니다.
- 타임라인 관련 컴포넌트들의 아토믹 패턴 단위를 재분류했습니다.
https://github.com/user-attachments/assets/b71175b8-cf0d-4b8a-b583-5fde5386b243
- 타임라인을 내릴때 자동으로 헤더의 날짜가 넘어가는 부분을 어떻게 구현할지 고민중입니다.

design: 타임라인 디자인 추가

---

app/record-detail/[id]/page.tsx
components/molecules/index.ts
components/molecules/modal/index.ts
components/molecules/modal/modal.tsx
features/record-detail/components/cheer-bottom-sheet.tsx
features/record-detail/components/cheer-modal-item.tsx
features/record-detail/components/cheer-modal.tsx
features/record-detail/components/index.ts
features/record-detail/sections/detail-cheer.tsx
hooks/index.ts
hooks/use-bottom-sheet.ts
hooks/use-dialog.ts
hooks/use-modal.ts
hooks/use-prevent-body-scroll.ts
store/index.ts
store/modal.ts

-
- 기록 상세 페이지에서만 사용되는 모달 컴포넌트를 정의합니다.
- 모달은 bottomSheet와 사용 방법이 유사합니다. (useModal hook)
- 화면의 너비에 따라 가변 너비를 가집니다 (600px 이상일 때는 고정 너비)
- 우선은 기록 상세에서만 사용되고, 별도의 optional 요소가 디자인상으로 존재하지 않아 스토리북 파일을 추가하지 않았지만, 필요하다면 추후 추가하도록 하겠습니다. 
- figma
-

feat: modal component를 구현합니다.

---

app/record-detail/[id]/page.tsx
components/atoms/dim/dim.tsx
components/molecules/bottom-sheet/bottom-sheet.tsx
components/molecules/dialog/dialog.tsx
components/molecules/index.ts
components/molecules/modal/index.ts
components/molecules/modal/modal.tsx
features/record-detail/components/cheer-bottom-sheet.tsx
features/record-detail/components/cheer-modal-item.tsx
features/record-detail/components/cheer-modal.tsx
features/record-detail/components/index.ts
features/record-detail/sections/detail-cheer.tsx
hooks/index.ts
hooks/use-bottom-sheet.ts
hooks/use-dialog.ts
hooks/use-modal.ts
hooks/use-prevent-body-scroll.ts
store/index.ts
store/modal.ts

- modal, bottomsheet, dialog가 중첩되는 상황이 발생합니다.
- modal, bottomsheet, dialog의 container와 dim 의 쌓임 정책을 정의합니다.
우선은 다음과 같이 정의했습니다.
요소 추가 시, 참고 부탁드립니다.
*   BottomSheet - dim: 500 / container: 550
*   Modal - dim: 700 / container: 750
*   Dialog - dim: 800 / container: 850
-
-

style: dim component의 쌓임 정책을 정의합니다

---

features/main/components/calendar/molecules/calendar.tsx
features/main/components/time-line/organisms/time-line.tsx
features/main/types/time-line.ts

- 경로가 수정되지 않아 export / import가 제대로 되지 않았습니다
- 정확한 경로를 지정하여 수정하였습니다
-

fix: 메인 페이지 barrel export 빌드 에러 수정

---

components/atoms/button/button.tsx

- 코드 리뷰를 반영하여 코드를 수정했는데 1) 중복된 조건문 2) 그로 인한 JSX 구조의 파괴로 에러가 있었습니다 🙇🏻
- 로딩 아이콘이 왼쪽에 있고, 로딩 아이콘이 있을 때는 좌/우측 아이콘 없이 텍스트만 존재합니다.
따라서 왼쪽 아이콘 또는 로딩이 존재할 때, isLoading이 true라면 로딩 아이콘을 보여주고 아이콘이 true라면 왼쪽 아이콘을 보여주게 조건문을 수정했습니다. (둘 다 보여주는 로직은 존재하지 않습니다.)
-
-

fix: Button 컴포넌트의 코드를 수정했습니다.

---

app/google/oauth/index.tsx
app/kakao/oauth/index.tsx
types/authType.ts

- 로그인 후 /join/nickname으로 바로 라우팅 되어 회원가입을 진행했어도 계속 회원가입 과정을 거쳐야 하는 버그가 있었습니다.
- 백엔드와 상의 후 isSignUpComplete 필드를 추가하여 true일 경우(회원가입 진행) 메인으로 라우팅하고, false일 경우(첫 로그인)에 회원가입 과정을 거치도록 라우팅 경로를 수정했습니다.
https://github.com/user-attachments/assets/2d922a2f-1bad-4fd5-85fb-1fde96046d9d
로그인 시 발생하는 에러는 로컬에서만 발생하고 배포 환경에서는 발생하지 않으니 참고 해주세요 :)
-

fix: 무한 회원가입 버그를 수정했습니다.

---

app/api/apple/oauth/route.ts
app/apple/oauth/index.tsx
app/apple/oauth/page.tsx

- 애플 로그인 관련한 환경변수들이 undefined로 들어가 디버깅이 필요합니다.
- 현재 작업한 부분까지 push합니다. 단 기존 소셜 로그인과 로직이 달라 로직 자체보다 환경 변수가 잘 읽히는지를 중점으로 확인해야 할 것 같습니다!
-
-

feat: 애플 로그인 관련 로직을 작업합니다.

---

components/atoms/icons/index.ts
components/atoms/icons/triangle-arrow-icon-reverse.tsx
components/atoms/icons/triangle-arrow-icon.tsx
components/atoms/icons/types.ts
features/main/components/calendar/atoms/move-month-button.tsx
features/main/components/calendar/molecules/calendar-header.tsx

- 사파리에서 svg가 rotate되지 않는 버그가 존재했습니다.
- 반대방향 화살표의 이미지를 컴포넌트화하여 사용하였습니다.
|as-is|to-be|
|------|---|
|![스크린샷 2024-08-20 오후 10 36 52](https://github.com/user-attachments/assets/96dc2397-7957-4257-a570-4dec60ee550a)|![스크린샷 2024-08-20 오후 10 36 34](https://github.com/user-attachments/assets/a671e1d5-3a12-4ac8-acca-dca9a3d89dc4)|
-

fix: 사파리에서 달력 화살표가 돌아가는 현상 수정

---

features/record/apis/use-search-pool-initial.ts
features/record/apis/use-search-pool.ts
features/record/components/organisms/pool-search-page-modal.tsx
features/record/components/organisms/pool-search-result-list.tsx
features/record/components/skeleton/pool-search-skeleton.tsx
panda.config.ts

- 수영장 검색 모달에 스켈레톤 UI를 Suspense fallback에 적용하였습니다.
- 스켈레톤 애니메이션
https://github.com/user-attachments/assets/c99a1e1c-49e0-4d42-97b8-59c6e691ed6a
- 수영장 초기 데이터 로딩
https://github.com/user-attachments/assets/1cc71906-9b29-4510-ac00-46c4c5127bb3
- 수영장 검색 데이터 로딩
https://github.com/user-attachments/assets/96eaa67e-2b69-49b0-b4a3-efa2227f6266
- NA

chore: 수영장 검색 시 스켈레톤 UI 적용

---

utils/icons.ts

- 사라진 타입에 대한 조건을 다루고 있어 빌드 에러가 발생하였습니다.
- 조건을 삭제하였습니다.
-

fix: 사라진 타입에 대한 조건 삭제

---

app/record-detail/[id]/page.tsx
features/record-detail/sections/detail-cheer-fab.tsx
features/record-detail/sections/detail-cheer-modal.tsx
features/record-detail/sections/index.ts

- 한 section 내부에서 많은 상태 변화가 발생하여 리렌더링을 야기합니다
- fab, modal section을 분리함으로써 상태 변화를 최소화하고, 흐름을 파악하기 쉽게 정리합니다
-
-

refactor: 응원하기 fab, modal section을 분리합니다

---

app/api/memory/reaction/route.ts
app/api/reaction/route.ts
app/record-detail/[id]/page.tsx
features/record-detail/apis/index.ts
features/record-detail/apis/use-cheer.tsx
features/record-detail/components/cheer-bottom-sheet.tsx
features/record-detail/components/cheer-progress.tsx
features/record-detail/components/index.ts
features/record-detail/data/index.ts
features/record-detail/sections/detail-cheer-fab.tsx
features/record-detail/sections/detail-cheer-modal.tsx
features/record-detail/sections/detail-cheer.tsx
features/record-detail/sections/index.ts
features/record-detail/types/index.ts

-
- 응원하기 api를 연동합니다
- 단순 api 파일 추가건입니다. (테스트를 위한 연동)
-
-

feat: 응원하기 api를 연동합니다

---

app/api/memory/[memoryId]/reactions/route.ts
app/api/memory/reaction/route.ts
app/api/reaction/route.ts
app/record-detail/[id]/page.tsx
features/record-detail/apis/index.ts
features/record-detail/apis/use-cheer-preview-list.tsx
features/record-detail/apis/use-cheer.tsx
features/record-detail/components/cheer-bottom-sheet.tsx
features/record-detail/components/cheer-progress.tsx
features/record-detail/components/date-picker.tsx
features/record-detail/components/index.ts
features/record-detail/components/swim-stats-item.tsx
features/record-detail/data/index.ts
features/record-detail/sections/detail-cheer-fab.tsx
features/record-detail/sections/detail-cheer-modal.tsx
features/record-detail/sections/detail-cheer.tsx
features/record-detail/sections/detail-preview.tsx
features/record-detail/sections/index.ts
features/record-detail/types/index.ts

-
- 기록 상세 페이지 상단에 노출되는 응원 미리보기 api를 연동합니다. 
- 본인/타인의 기록 상세 페이지에 대한 UI 분기처리를 진행합니다.
(참고) 아직 응원 미리보기 데이터가 없어 보여지지 않습니다!
- 본인의 기록 상세 페이지
- 타인의 기록 상세 페이지
-

feat: 응원 미리보기 (20개) api를 연동합니다

---

apis/fetch-data.ts

- fetch에 부여할 수 있는 중요한 요소인 nextTag와 cacheOption을 handling해야 했습니다.
- fetchData에 매개변수를 추가하였습니다.
- NA
- fetchData를 사용하고 있는 곳이 많아 우선 매개변수로 추가하였지만, 해당 방식으로 하면 외부에서 사용하지 않을 값에는 undefined를 무조건 넣어주어야 합니다. 추후 객체 타입으로 수정하는게 나을 수도 있어 보입니다.

refactor: fetchData 함수에 매개변수 추가

---

features/profile/components/organisms/other-page.tsx

- 아직 개발중인 api를 실수로 같이 commit 해서 되돌립니다... 😞
-
-
-

fix: 잘못한 commit 수정합니다.

---

features/record-detail/components/swim-tool-item.tsx
features/record/components/molecules/equipment-select-box.tsx
features/record/components/organisms/equipment-section.tsx

- 각 장비에 맞는 이미지들을 연결하였습니다.
- NA

chore: 장비 section에 각 장비에 맞는 이미지 연결

---

components/molecules/global-navigation-bar/global-navigation-bar.tsx

- 홈 or 소식 페이지에서 스크롤을 하면 일부 요소가 GNB에 가려지는 현상이 있습니다.
- GNB의 placeholder dom을 설정해 주었습니다.
https://github.com/user-attachments/assets/6595d645-ceb3-4ba8-86c6-f1b227ea84c7
- NA

fix: gnb의 placeholder dom 설정

---

app/api/memory/reaction/[reactionId]/route.ts
features/record-detail/apis/index.ts
features/record-detail/apis/use-cheer-remove.tsx
features/record-detail/components/cheer-modal-item.tsx
features/record-detail/components/cheer-modal.tsx
hooks/index.ts

-
- 응원 삭제 api를 추가하고 연동합니다.
(+) 동작은 영상 참고 
1. 응원 삭제 시 어떤 모달까지 닫혀야 할지 디자인 문의 후 수정 예정
2. 응원 삭제 시, 받아오는 응답 값 수정 요청 후 반영 예정
https://github.com/user-attachments/assets/e94399e8-ef40-408a-a3b4-47aa0984c093
-

feat: 응원 삭제 api를 연동합니다

---

app/api/memory/[memoryId]/reactions/detail/route.ts
app/api/memory/reaction/[reactionId]/route.ts
components/molecules/modal/modal.tsx
features/record-detail/apis/index.ts
features/record-detail/apis/use-cheer-list.tsx
features/record-detail/apis/use-cheer-remove.tsx
features/record-detail/components/cheer-modal-item.tsx
features/record-detail/components/cheer-modal.tsx
features/record-detail/sections/detail-cheer-modal.tsx
hooks/index.ts
package.json
pnpm-lock.yaml

- 
- 응원 목록 api를 연동합니다
- 무한 스크롤 방식을 사용합니다
- virtual infinite scroll을 사용하기 위해 Virtuoso 라이브러리를 세팅합니다.
- 클릭한 아이템의 index를 기준으로. 상단 노출될 게시물을 결정합니다. 
-
https://github.com/user-attachments/assets/cc63659f-bcc3-44bf-8303-88732c93bb6f
-

feat: 응원 목록 api를 연동합니다.

---

features/record-detail/components/swim-tool-item.tsx
features/record/components/molecules/equipment-select-box.tsx

fix: 잘못 변경된 수영 도구 사진 size 수정

---

app/record-detail/[id]/page.tsx

feat: 기록 상세 페이지  meta data 추가

---

app/record-detail/[id]/page.tsx

feat: open graph tag 추가

---

features/main/components/calendar/molecules/calendar-header.tsx

- 피그마보다 달력의 헤더 버튼이 더 벌어져있었습니다.
- gap 속성을 삭제하여 피그마와 비슷하게 수정하였습니다.
-
-

design: 달력 헤더의 달 이동 버튼 간격 수정

---

features/setting/apis/index.ts

- 제거 누락된 export 코드로 빌드 에러가 발생하였습니다.
- 해당 코드를 삭제하였습니다.
-
-

fix: 존재하지 않는 파일 export 제거

---

features/record/hooks/use-distance-page-modal.tsx

chore: 수영 거리 입력 완료 시 나타나는 버튼 텍스트 수정

---

features/record/components/molecules/pool-search-result-element.tsx
features/record/components/organisms/pool-search-page-modal.tsx
features/record/components/organisms/pool-search-result-list.tsx
features/record/index.ts
features/record/utils/highlight-text.tsx
features/record/utils/index.ts
features/record/utils/remove-special-symbols.ts
hooks/revalidateCurrentMemberInfo.ts

https://github.com/user-attachments/assets/b8c1b743-7532-45a0-803e-8cb74fcac663
- NA

design: 수영 검색 텍스트와 일치하는 부분을 highlight 되도록 디자인을 수정합니다.

---

components/molecules/modal/modal.tsx

- 사파리에서 모달의 Height 값이 잘못 계산됩니다
- height full 옵션을 제거하고, max-content 값으로 변경합니다
-

fix: modal style 변경

---

app/layout.tsx

-
- 화면 확대, 축소를 막기 위해 viewport meta 속성을 추가합니다
-
-

feat: viewport metatag 추가

---

components/atoms/icons/date-arrow-icon.tsx
features/record-detail/components/date-picker.tsx
features/record-detail/sections/detail-preview.tsx

- 
- 기록 상세 페이지 버튼 스타일을 변경합니다
-
-

feat: 기록 상세 페이지 DatePicker button 스타일 변경

---

.github/workflows/build-test.yml

- 빌드 에러를 놓히는 경우가 자주 발생하였습니다.
- GitHub Actions에 빌드 테스트를 추가하였습니다.
-
-

chore: 빌드테스트 액션 추가

---

features/record-detail/components/cheer-modal-item.tsx
features/record-detail/components/cheer-modal.tsx
features/record-detail/types/index.ts

-
- 응원 모달 내부의 프로필을 클릭하면, 해당 프로필 페이지로 이동하는 로직을 추가합니다
-
https://github.com/user-attachments/assets/8ca5e803-df4b-41ac-ab76-101e549e110c
-

feat: memberId 이동기능 추가

---

.github/workflows/build-test.yml

- GitHub Actions 빌드 테스트 중, 스타일 모듈을 찾지 못하여 빌드가 실패하였습니다.
- module install 이후에 css 코드를 생성할 수 있도록 코드를 추가하였습니다.
-

fix: css code generate 추가

---

app/loading.tsx

-
- 라우팅 이동시에 출력되는 임시 로딩 페이지를 추가합니다 (디자인 나오면 교체 필요)
-
https://github.com/user-attachments/assets/2de10df4-0929-489f-a228-9071cfd272df
-

feat: 라우팅 이동 시에 출력되는 loading UI를 추가합니다

---

app/profile/[id]/follow/page.tsx
app/record-detail/[id]/page.tsx
components/molecules/profile-list-item/profile-list-item.tsx
features/follow/apis/use-follower-list.tsx
features/follow/apis/use-following-list.tsx
features/follow/components/follow-virtual-list.tsx
features/record-detail/apis/use-cheer-list.tsx

-
- 프로필 팔로우 페이지에 구현한 컴포넌트를 적용합니다
- 
https://github.com/user-attachments/assets/9ecb44e1-9aa1-4d9d-afe7-01e4a2be3fc0
-

feat: profile follow 페이지 컴포넌트 적용

---

app/api/friend/[memberId]/follower/route.ts
app/api/friend/[memberId]/following/route.ts
app/profile/[id]/follow/page.tsx
app/record-detail/[id]/page.tsx
components/molecules/profile-list-item/profile-list-item.tsx
features/follow/apis/index.ts
features/follow/apis/use-follower-list.tsx
features/follow/apis/use-following-list.tsx
features/follow/components/follow-virtual-list.tsx
features/follow/components/index.ts
features/follow/sections/follower-section.tsx
features/follow/sections/following-section.tsx
features/follow/sections/index.ts
features/follow/types/index.ts
features/record-detail/apis/use-cheer-list.tsx

-
- 팔로우, 팔로잉 리스트 조회 api를 정의합니다
-
-

feat: follower, following api 정의

---

app/api/notification/read/route.ts
app/notification/page.tsx
features/notification/apis/dto/notification.ts
features/notification/apis/use-read-notification.tsx
features/notification/components/molecules/notification-element.tsx

- 알림 읽음 처리를 구현합니다(background color 차이).
https://github.com/user-attachments/assets/dda8ed1f-0fa5-4f4d-ab7e-2674c862027b
- NA

feat: 알림 읽음 처리 기능 구현

---

features/profile/components/organisms/my-page.tsx

- 프로필 편집 페이지로의 라우팅을 생성합니다.
https://github.com/user-attachments/assets/e0c3d89a-a70d-463c-b666-c1dbca570125
- NA

chore: 프로필 편집 라우팅 추가

---

features/record/utils/remove-special-symbols.ts

chore: 정규식 한글 허용

---

components/molecules/page-modal/page-modal.tsx

- Page modal이 IOS에서 이상하게 동작하였습니다.
- vh -> dvh로 수정하였습니다.
- NA
- NA

fix: vh -> dvh로 수정

---

features/follow/sections/follow-tab.tsx

- history stack이 계속 쌓입니다.
- push > replace event로 변경합니다
-
-

feat: follow tab query change event 변경

---

features/profile/apis/dto/profile-image-url-done.ts
features/profile/apis/use-profile-image-url-done.ts
features/profile/components/atoms/default-profile.tsx
features/profile/components/organisms/profile-container.tsx
features/profile/components/organisms/profile-edit-form.tsx
features/profile/components/organisms/profile-edit-image-section.tsx
features/profile/components/organisms/profile-image-bottom-sheet.tsx
features/profile/hooks/use-profile-edit-form.tsx
features/profile/hooks/use-profile-image-bottom-sheet.tsx
features/profile/types/profile-edit-image.ts
features/profile/types/profile.ts
public/images/default-profile/index.ts

- 프로필 이미지 수정 기능을 구현했습니다..
- 디폴트 프로필로 수정
https://github.com/user-attachments/assets/8cac98c1-2c8e-44d0-b4d8-ebf1fa14c175
- 사진으로 수정
https://github.com/user-attachments/assets/7b4aef39-300f-4637-9836-59c3ca03dcf8
- 디폴트 프로필 + 닉네임 수정
https://github.com/user-attachments/assets/fda5f758-2fc7-4c04-94f0-2c67fb2d9891
- 모두 수정
https://github.com/user-attachments/assets/0969e3a5-b68c-4950-8c6a-e8ae5645b805
- 모두 ProfileImage로 구현 시, 바텀시트에서 디폴트 프로필 클릭시 UI가 바뀌지 않는다거나 선택을 해도 UI에 반영되지 않아서 우선 새 컴포넌트와 함께 사용하였습니다.

feat: 프로필 이미지 수정 기능을 구현하여 모든 프로필 수정 로직을 완료합니다.

---

components/molecules/profile-list/profile-list-skeleton.tsx
components/molecules/profile-list/profile-list.tsx
features/follow/sections/follower-section.tsx
features/follow/sections/following-section.tsx
features/profile-search/sections/search-result-section.tsx
panda.config.ts

-
- profile list component의 skeleton을 적용합니다
- profile list next page 데이터를 불러올 경우, 하단에 노출되는 loading ui를 추가합니다
https://github.com/user-attachments/assets/6b704064-12fe-47be-85b6-9abbcf52a4f6
-

feat: profile list skeleton을 적용합니다

---

app/profile/[id]/follow/page.tsx
components/molecules/profile-list/profile-list-skeleton.tsx
components/molecules/profile-list/profile-list.tsx
features/follow/components/empty-follow-list.tsx
features/follow/components/index.ts
features/follow/sections/follow-tab.tsx
features/follow/sections/follower-section.tsx
features/follow/sections/following-section.tsx
features/follow/types/index.ts
features/profile-search/sections/search-result-section.tsx
features/profile/components/organisms/profile-container.tsx
panda.config.ts

팔로우/팔로잉 페이지를 개선합니다
- BE와 통일성을 가지기 위해 followTab type을 변경합니다
- empty case를 추가합니다
- isFetching > isLoading 사용으로 변경합니다 (initial load)
- 마이페이지 > 팔로우 페이지 동선을 연결합니다
-

feat: empty case 추가 및 follow tab type 변경

---

features/profile/components/organisms/my-page.tsx
features/profile/components/organisms/profile-edit-form.tsx

fix: 프로필 데이터 예외 처리

---

features/news/components/atoms/find-member-button.tsx

feat: search page 동선 추가

---

features/profile/components/organisms/profile-edit-form.tsx
features/profile/components/organisms/profile-edit-image-section.tsx

- introduction 필드에 예외처리를 적용합니다.
- NA
- NA

chore: introduction 예외처리

---

components/molecules/global-navigation-bar/global-navigation-bar.tsx
components/molecules/global-navigation-bar/use-global-navigation-bar.tsx

- 마이페이지에서 새로고침 시 -> gnb가 "마이"에 고정되지 않았습니다.
- 유저정보를 가져온 후에 gnb index를 결정해주는 로직을 추가하였습니다.
- before & after
https://github.com/user-attachments/assets/94486133-7a0d-4ef4-b6bf-8b0140128300
https://github.com/user-attachments/assets/f4ac404f-1d83-4f6c-a2e4-b15b704cf3de
- NA

fix: 마이 프로필 페이지에서 새로고침 시, gnb focus가 이동되는 현상 수정

---

app/record/success/page.tsx

-
- 수영 기록 생성 시 나타나는 텍스트를 수정하였습니다.
- NA

chore: 수영 기록 생성 성공 시 텍스트 수정

---

app/api/apple/oauth/route.ts

- 최초 회원가입 시에만 user 데이터가 전달되기 때문에 해당 값을 옵셔널 처리합니다.
-
-

fix: user 값을 옵셔널 처리합니다.

---

features/main/components/calendar/atoms/calendar-item.tsx
features/main/components/calendar/molecules/calendar.tsx
features/main/hooks/use-calendar-rendering-data.ts

- 달력에서 미래의 날짜에 대해 클릭을 하여 기록이 가능했습니다.
- 오늘 이후의 날짜인지 판별 후, 미래의 날짜에 대해서는 달력에서 클릭하지 못하도록 Link가 아닌 div로 설정해주었습니다.
-
-

feat: 달력에서 미래 날짜에 대해 클릭하지 못하도록 설정

---

features/news/components/molecules/news-item-wrapper.tsx
features/news/components/organisms/news-list.tsx

- API 스펙이 변경되었습니다.
- 스펙에 맞게 필드 이름을 수정하였습니다.
-
-

fix: 바뀐 스펙에 맞게 필드 이름 수정

---

components/molecules/cheer/cheer-bottom-sheet.tsx
components/molecules/cheer/cheer-item.tsx
components/molecules/cheer/cheer-progress.tsx
components/molecules/cheer/index.ts
components/molecules/index.ts
features/record-detail/components/index.ts
features/record-detail/sections/detail-cheer-fab.tsx
features/record-detail/sections/detail-cheer-modal.tsx
hooks/index.ts
hooks/use-cheer-bottom-sheet.ts

refactor: cheer bottom sheet를 분리합니다

---

components/molecules/cheer/cheer-bottom-sheet.tsx
components/molecules/cheer/cheer-item.tsx
components/molecules/cheer/cheer-progress.tsx
components/molecules/cheer/index.ts
components/molecules/index.ts
features/main/components/calendar/molecules/calendar.tsx
features/record-detail/components/index.ts
features/record-detail/sections/detail-cheer-fab.tsx
features/record-detail/sections/detail-cheer-modal.tsx
hooks/index.ts
hooks/use-cheer-bottom-sheet.ts

- 캘린더 컴포넌트 타입이 옵셔널하지 않아 발생한 이슈입니다
- 타입을 변경합니다
-
-

fix: 캘린더 빌드 에러 수정

---

components/molecules/cheer/cheer-bottom-sheet.tsx
features/news/components/atoms/cheer-up-button.tsx
features/news/components/molecules/news-item-wrapper.tsx
features/news/components/organisms/news-list.tsx

-
- 소식 페이지에서 응원하기 버튼을 이용하여 바텀시트를 호출하고 이를 통해 응원 기능을 사용할 수 있도록 추가하였습니다.
https://github.com/user-attachments/assets/2381432a-8486-4335-b7c0-73c623fcce05
-

feat: 소식 페이지 응원하기 버튼 연결

---

features/news/components/molecules/news-item-wrapper.tsx

feat: 소식 아이템의 프로필 클릭시 유저 페이지로 이동

---

features/news/components/atoms/following-list-link-button.tsx
features/news/components/molecules/empty-news.tsx

feat: 소식 페이지에서 Link 태그에 대한 라우팅을 정상적으로 추가

---

app/apple/oauth/index.tsx
app/layout.tsx
app/login/login-client.tsx
global.d.ts

feat: 애플 로그인 구현을 위한 테스트를 합니다.

---

app/login/login-client.tsx

style: image wrapper 스타일 변경

---

features/main/components/calendar/molecules/calendar.tsx

fix: 남의 캘린더 조회 수정

---

app/api/apple/oauth/route.ts
app/apple/oauth/index.tsx
app/login/login-client.tsx
global.d.ts

feat: 애플 로그인 구현 테스트 합니다.

---

app/api/apple/oauth/route.ts
app/apple/oauth/index.tsx

feat: 애플 로그인 구현 테스트 합니다. 

---

app/api/image/edit/[memoryId]/route.ts
app/api/notification/route.ts
components/molecules/header-bar/header-bar-notification-button.tsx
features/notification/apis/dto/notification.ts
features/notification/apis/use-get-notification.tsx
features/notification/components/molecules/cheer-notification.tsx
features/notification/components/molecules/follow-notification.tsx
features/notification/components/molecules/index.ts
features/notification/components/molecules/notification-element.tsx
features/notification/components/organisms/notification-list.tsx
features/notification/index.ts
features/notification/styles/index.ts
features/notification/styles/notification-element.ts
features/notification/types/notification.ts

- 알림 페이지의 모든 기능을 완료합니다.
https://github.com/user-attachments/assets/c575e355-ee67-4e4f-861f-76fba7a7bf5f
- NA

feat: 알림 페이지 내부 팔로우기능 연결 + 리팩토링 완료했습니다.

---

app/api/friend/route.ts
components/molecules/profile-list/profile-list-item.tsx
hooks/apis/use-following-state.ts

- 변경된 api 스팩을 적용합니다
- profile item에 말줄임을 적용합니다
-

feat: 변경된 follow api 스팩을 적용합니다

---

components/molecules/header-bar/header-bar-notification-button.tsx
components/molecules/profile-list/profile-list-item.tsx
features/main/components/calendar/atoms/calendar-item-content.tsx
features/main/components/time-line/molecules/time-line-card.tsx
features/record-detail/components/cheer-modal-item.tsx
features/record-detail/sections/detail-diary.tsx

- 사파리에서 dot 의 위치가 다릅니다
- 프로필 이미지가 잘못 노출됩니다 + 성능 개선을 위한 sizes props가 누락되었습니다.
- dot의 위치를 수정합니다
- 프로필 이미지 스타일을 수정합니다
-
-

style: 스타일 관련 이슈를 수정합니다

---

features/notification/apis/use-get-notification.tsx
features/notification/components/molecules/follow-notification.tsx

- 알림 페이지에서 팔로우 상태를 sync 합니다.
https://github.com/user-attachments/assets/69cbe194-8c34-4e9b-9510-263ecf17ee92
- NA

feat: 알림 페이지에서 팔로잉 상태 싱크

---

features/main/components/calendar/atoms/calendar-item.tsx
features/main/components/calendar/molecules/calendar.tsx

- 다른 사람의 달력에서 기록이 가능했습니다.
- 현재 로그인한 유저의 달력인지를 확인하고, 아니라면 기록을 비활성화하였습니다.
-
-

fix: 다른 사람의 달력에서 기록이 가능한 버그 수정

---

features/profile/components/organisms/my-page.tsx

- 마이페이지에서 프로필 공유 기능이 추가되었습니다.
- toast와 clipboard로 url을 복사했습니다.
https://github.com/user-attachments/assets/192eda5b-8cab-47b1-b3df-8c52db927afb
-

feat: 프로필 공유 기능 구현합니다.

---

features/record/components/organisms/distance-page-modal.tsx
features/record/components/organisms/pool-search-page-modal.tsx
hooks/index.ts
hooks/use-prevent-router-back.tsx

-
- page-modal이 열려있을 때, 뒤로가기를 방지하는 훅을 생성합니다.
-
-

chore: 뒤로가기 감지 훅 적용

---

app/page.tsx
features/main/components/calendar/molecules/calendar.tsx
features/main/components/main-tab/main-tab.tsx
features/main/components/time-line/molecules/time-line-card.tsx
features/main/components/time-line/organisms/index.ts
features/main/components/time-line/organisms/time-line-skeleton.tsx
features/main/components/time-line/organisms/time-line.tsx

- 타임라인 스켈레톤을 적용합니다
- 탭 방식을 변경합니다
-
https://github.com/user-attachments/assets/4d950333-2aaa-4bba-8fad-97da0b5840f1
- 데이터 로딩 시간보다 컴파일 시간이 더 느려서 Dynamic loading + 데이터 로딩 둘 다 스켈레톤을 적용했습니다.
더 좋은 방법을 찾아보는 것이 좋을 것 같아요

feat: 타임라인 스켈레톤 적용

---

features/main/components/calendar/atoms/calendar-header-skeleton.tsx
features/main/components/calendar/atoms/calendar-item-layout.tsx
features/main/components/calendar/atoms/calendar-item-skeleton.tsx
features/main/components/calendar/atoms/calendar-item.tsx
features/main/components/calendar/atoms/index.ts
features/main/components/calendar/atoms/user-profile-skeleton.tsx
features/main/components/calendar/molecules/calendar.tsx
features/main/components/calendar/organisms/user-calendar-profile.tsx

-
-
- 첫 달력 렌더링 전 스켈레톤 적용
https://github.com/user-attachments/assets/3fd2ae4e-d0d5-4766-991b-dd73fb16f424
- 렌더링 이후 달 이동시 스켈레톤 적용
https://github.com/user-attachments/assets/1f5470d7-93ec-4abc-91f9-1577a6efa708
-

design: 달력 스켈레톤 적용

---

components/atoms/icons/date-arrow-icon.tsx
components/molecules/cheer/cheer-item.tsx
components/molecules/record-mark/record-mark.tsx
features/record-detail/components/date-picker.tsx
features/record-detail/sections/detail-cheer-modal.tsx
panda.config.ts

-
- 기록 상세에 미노출하던 버튼 영역을 스타일 변경하는 것으로 처리합니다
- 기록 상세 상단의 응원 리스트에 애니메이션을 적용합니다
- 캘린더에 animation 효과를 추가합니다
- 기록상세
https://github.com/user-attachments/assets/da626366-ae15-475f-bf4a-d5a37f2c554e
- 캘린더
https://github.com/user-attachments/assets/945886c4-d6c1-4b4c-837b-2eb5be7f6c6e
-

feat: 기록 상세 버튼 활성화 조건 수정

---

features/main/components/calendar/atoms/calendar-item.tsx

fix: 달력 아이템 아래 총 거리 폰트 크기 원복

---

components/molecules/dialog/dialog.tsx
features/setting/apis/index.ts
features/setting/apis/use-logout.ts
features/setting/components/organisms/step-3.tsx
features/setting/hooks/index.ts
features/setting/hooks/use-delete-dialog-handler.ts
features/setting/hooks/use-logout-dialog-handler.ts

-
- dialog의 경우 버튼이 2개인 게 디폴트여서 1개일 때는 우측으로 정렬되게 수정했습니다.
- 탈퇴하기가 성공하면 로그아웃 + 탈퇴를 하고 모달이 띄워집니다. 모달의 확인을 누르면 라우팅됩니다. 로그아웃되어 있기 때문에 시간이 지나면 미들웨어로 인해 /login으로 라우팅됩니다.
https://github.com/user-attachments/assets/0d4d7fb2-9a4a-4eca-ba12-af37bfc2503e
- todo 참고 부탁드립니다.
- dim의 close를 추후 수정해야 할 것 같습니다.

feat: 탈퇴 시 모달이 나오게 구현했습니다.

---

app/api/apple/oauth/route.ts
features/login/components/organisms/login-screen.tsx

feat: 애플 로그인 구현 테스트

---

components/atoms/image/image.tsx

- 이미지 src가 갱신되지 않습니다
관련 이슈: https://www.notion.so/depromeet/QA-928fc7eb7e8840cc8899a7e014ecaa3f?p=91ec1ce445494654a1c0037f7757a4e7&pm=s
- useEffect로 갱신 로직을 추가합니다
https://github.com/user-attachments/assets/d533f42c-20a4-409c-856a-cb3572240a4c
-

fix: image src use effect 갱신 로직 추가

---

features/main/components/time-line/organisms/time-line.tsx

fix: 빈 타임라인 테스트용 조건문 원복

---

features/profile/components/molecules/profile-container-skeleton.tsx

feat: 스켈레톤 문구 임시 주석처리

---

app/layout.tsx
features/notification/apis/use-get-notification.tsx
features/notification/components/organisms/notification-list.tsx
features/record/apis/use-search-pool.ts
features/record/components/organisms/pool-search-result-list.tsx

-
- 무한스크롤 로딩 상태를 추가합니다.
- 알림
https://github.com/user-attachments/assets/7bb0839d-8bfb-4d55-b294-3bce8f9731cd
- 수영장 검색
https://github.com/user-attachments/assets/89d326db-3d6a-4865-a306-16944937f463
- NA

chore: 무한스크롤 로딩 상태를 추가합니다.

---

app/setting/page.tsx
features/setting/hooks/index.ts
features/setting/hooks/use-notice-dialog.handler.ts

- 설정 페이지에서 아직 개발 되지 않은 부분들이 있습니다.
- 개발중임을 알리는 모달을 띄웠습니다. 
https://github.com/user-attachments/assets/259e8893-7a92-475f-a25c-86748994722e
-

feat: 미작업 페이지 클릭 시 노출되는 고지 모달

---

app/setting/page.tsx

- 문의하기 링크가 추가됐습니다.
- 스위미에게 문의하기 클릭 시 새 창을 열도록 수정했습니다.
https://github.com/user-attachments/assets/438149c7-b5b9-45da-907a-73be0b08034b
-

feat: 문의하기 클릭 시 구글폼으로 이동하는 기능 추가합니다.

---

features/record/components/organisms/form.tsx

-
- 이전 기록 정보를 불러올 때 로딩 UI를 띄워주었습니다.
https://github.com/user-attachments/assets/f76effbe-a598-4b98-85f6-fd964667642d
- NA

chore: 기록 정보 불러올 때 로딩 상태 추가

---

features/record/components/organisms/form.tsx

- 배포에서 item 이 업데이트 되지 않습니다.
- item을 업데이트 하는 로직을 추가합니다.
- NA
- NA

chore: item 코드 추가

---

app/join/finish/page.tsx
app/join/gender/page.tsx

fix: 온보딩 페이지의 버튼 높이 수정 및 가입 완료 페이지 높이 수정

---

features/news/components/organisms/news-list.tsx

refactor: ptr 주석처리

---

components/molecules/text-field/form-text-field.tsx
features/record/components/organisms/sub-info-text-fields.tsx

- maxLength가 적용이 UI에서 되지 않았습니다.
- maxLength를 적용하는 코드를 추가하였습니다.
- NA
- NA

chore: maxLength 적용

---

features/setting/hooks/use-logout-dialog-handler.ts

- 로그아웃 시 메인 페이지로 갑니다.
- /login으로 수정합니다.
-
-

fix: 로그아웃 시 경로 수정합니다.

---

features/login/components/organisms/login-screen.tsx

chore: 애플 로그인 버튼을 다시 노출합니다.

---

app/api/apple/oauth/route.ts

chore: 애플 로그인 구현 테스트

---

app/api/apple/oauth/route.ts
app/apple/test/index.tsx

chore: 애플 로그인 구현 테스트

---

app/api/apple/oauth/route.ts
features/login/components/organisms/login-screen.tsx
global.d.ts

feat: 애플 로그인 구현 테스트합니다.

---

app/api/apple/oauth/route.ts
app/apple/test/index.tsx
features/login/components/organisms/login-screen.tsx

fix: 원채 버전으로 수정합니다.

---

app/api/apple/oauth/route.ts
app/apple/test/index.tsx
app/kakao/oauth/index.tsx

feat: 애플 로그인 구현 테스트 중

---

app/apple/test/index.tsx
app/kakao/oauth/index.tsx

fix: 코드 수정

---

features/login/components/organisms/login-screen.tsx

-
Apple ID로 로그인 -> **Apple로 로그인** 으로 수정
-

chore: 앱 심사를 위한 애플 로그인 버튼 문구 수정합니다.

---

app/join/gender/page.tsx
components/atoms/button/button.tsx

- ios 앱 출시 리젝 사유 중 성별을 남성/여성으로만 표기하는 것이 있어, 무성에 해당되는 버튼을 추가했습니다.
버튼을 추가하고 서버와 논의하여 무성에 해당되는 버튼은 'N'으로 전달합니다.
[피그마 시안]
https://github.com/user-attachments/assets/14d5bd80-537a-4b6e-b61d-4bec767c8571
- Button 컴포넌트에 높이를 설정해놔서 런타임 시 적용이 안됐습니다. 주석 처리했고 타 페이지에 지장 없는 점 확인했는데 혹시 몰라 코드를 지우진 않고 주석처리 했습니다. 
- 현재 서버가 아직 변경사항을 반영하지 않아 지금 위에선 에러가 납니다. 배포 후 확인해보겠습니다.

feat: 성별 선택하지 않기 버튼 추가합니다.

---

features/login/components/organisms/login-screen.tsx

-
- 웹뷰 403 에러로 인해 잠시 삭제합니다.
-
-

chore: 임시 구글로그인 주석처리

---

app/setting/page.tsx

- 앱 출시 시 미구현 영역을 모달로 대체하면 리젝 될 수 있다고 합니다.
- 미구현 영역인 '오픈소스 라이선스'를 아예 주석처리하여 제외합니다.
[as is]
[to be]
- 이 부분은 어떻게 완성할지 논의가 필요해보입니다!

chore: 앱 심사를 위해 미구현 영역 주석 처리합니다.

---

features/main/components/calendar/atoms/calendar-item.tsx

- 달력에서 disable된 날짜에 대한 처리가 없었습니다.
- toast 처리를 통해 유저에게 내용을 알려주었습니다.
- 메인 페이지 미래 날짜 관련 토스트
https://github.com/user-attachments/assets/5c5a9fe8-ef7a-4716-8970-31adf3796bb9
- 다른 유저의 페이지 달력의 날짜 관련 토스트
https://github.com/user-attachments/assets/f3a40b54-c9fd-4fd2-b360-d2b913692fdb
-

feat: 기록할 수 없는 달력 날짜에 대한 토스트 추가

---

features/profile/components/atoms/follow-button.tsx
hooks/apis/use-following-state.ts

- 팔로우, 팔로잉 카운트 갱신을 위해 onSuccess 로직을 추가합니다. 
-
-

feat: following, follower count 갱신

---

components/atoms/button/button.tsx
components/atoms/button/index.ts
components/atoms/button/type.ts
components/molecules/dialog/dialog.tsx
features/record-detail/components/cheer-modal.tsx
features/setting/hooks/use-delete-dialog-handler.ts
features/setting/hooks/use-logout-dialog-handler.ts
features/setting/hooks/use-notice-dialog.handler.ts
features/setting/hooks/use-save-dialog-handler.ts

-
- button component에 negative option을 추가합니다
- dialog component의 버튼 영역에서 모든 button props를 받을 수 있도록 수정합니다
-
-

feat: button/dialog component 확장 및 적용

---

app/record-detail/[id]/page.tsx
app/setting/blocked/page.tsx
app/setting/page.tsx
components/molecules/profile-list/profile-blocked-list-item.tsx
components/molecules/profile-list/profile-list.tsx
features/setting-blocked/components/empty-blocked-list.tsx
features/setting-blocked/components/index.ts
features/setting-blocked/index.ts
features/setting-blocked/sections/blocked-list-section.tsx
features/setting-blocked/sections/index.ts

-
- 차단 리스트 페이지를 구현합니다 (진입점 생성)
- BE 미배포 사항입니다
- 차단 해제하기 api 연동
-
-

feat: 차단 리스트 페이지를 구현합니다

---

app/api/member/black/route.ts
app/record-detail/[id]/page.tsx
app/setting/blocked/page.tsx
app/setting/page.tsx
components/molecules/profile-list/profile-blocked-list-item.tsx
components/molecules/profile-list/profile-list.tsx
features/setting-blocked/apis/index.ts
features/setting-blocked/apis/use-blocked-list.tsx
features/setting-blocked/components/empty-blocked-list.tsx
features/setting-blocked/components/index.ts
features/setting-blocked/index.ts
features/setting-blocked/sections/blocked-list-section.tsx
features/setting-blocked/sections/index.ts
features/setting-blocked/types/index.ts

feat: 차단 리스트 관련 api를 추가합니다

---

app/api/member/black/route.ts
app/record-detail/[id]/page.tsx
app/setting/blocked/page.tsx
app/setting/page.tsx
components/molecules/dialog/dialog.stories.tsx
components/molecules/profile-list/profile-blocked-list-item.tsx
components/molecules/profile-list/profile-list.tsx
features/record-detail/components/index.ts
features/record-detail/components/report-bottom-sheet.tsx
features/record-detail/index.ts
features/record-detail/sections/detail-report-fab.tsx
features/record-detail/sections/index.ts
features/record-detail/types/index.ts
features/setting-blocked/apis/index.ts
features/setting-blocked/apis/use-blocked-list.tsx
features/setting-blocked/components/empty-blocked-list.tsx
features/setting-blocked/components/index.ts
features/setting-blocked/index.ts
features/setting-blocked/sections/blocked-list-section.tsx
features/setting-blocked/sections/index.ts
features/setting-blocked/types/index.ts

-
- 기록 신고하기 기능을 구현합니다 (BE 미배포)
- 메뉴 컴포넌트 미개발로 임시 주석처리 해놨습니다.
https://github.com/user-attachments/assets/75034d6d-7cbf-4fcd-8b59-246c0140cfb0
-

feat: 기록 신고하기 기능 구현 및 페이지 적용 (임시 주석처리)

---

app/api/member/black/route.ts
app/api/report/route.ts
app/record-detail/[id]/page.tsx
app/setting/blocked/page.tsx
app/setting/page.tsx
components/molecules/dialog/dialog.stories.tsx
components/molecules/profile-list/profile-blocked-list-item.tsx
components/molecules/profile-list/profile-list.tsx
features/record-detail/apis/index.ts
features/record-detail/apis/use-report.tsx
features/record-detail/components/index.ts
features/record-detail/components/report-bottom-sheet.tsx
features/record-detail/index.ts
features/record-detail/sections/detail-report-fab.tsx
features/record-detail/sections/index.ts
features/record-detail/types/index.ts
features/setting-blocked/apis/index.ts
features/setting-blocked/apis/use-blocked-list.tsx
features/setting-blocked/components/empty-blocked-list.tsx
features/setting-blocked/components/index.ts
features/setting-blocked/index.ts
features/setting-blocked/sections/blocked-list-section.tsx
features/setting-blocked/sections/index.ts
features/setting-blocked/types/index.ts

-
-
-
- api 파일 export 작업건이 다음 PR에 포함되어 들어갔습니다! (해당 PR에서 빌드 에러 발생)

feat: 기록 신고하기 api 추가

---

app/record/page.tsx
components/atoms/icons/index.ts
components/atoms/icons/warn-icon.tsx
features/record/components/molecules/index.ts
features/record/components/molecules/record-warning.tsx
features/record/components/organisms/record-header-bar.tsx

- 기록 페이지에 경고 문구를 띄워주었습니다.
- NA

feat: 기록 페이지에 경고 문구를 생성합니다.

---

app/record/page.tsx
components/atoms/icons/index.ts
components/atoms/icons/warn-icon.tsx
features/record/components/atoms/delete-record-button.tsx
features/record/components/atoms/index.ts
features/record/components/molecules/index.ts
features/record/components/molecules/record-warning.tsx
features/record/components/organisms/index.ts
features/record/components/organisms/record-header-bar.tsx

- 
- 기록 삭제 기능과 관련된 헤더 및 dialog UI 구현
- 기록 생성 페이지 
- 기록 수정 페이지
- 기록 삭제 api 연결

feat: 기록 삭제 UI를 구현합니다.

---

app/record-detail/[id]/page.tsx
features/record-detail/components/report-bottom-sheet.tsx

feat: 신고하기 주석처리

---

app/api/black/route.ts
app/api/member/black/route.ts
features/profile/components/atoms/block-button.tsx
features/profile/components/molecules/other-page-header.tsx
features/profile/hooks/use-block-dialog-handler.tsx
features/profile/hooks/use-block-member.ts

- 405 에러
- api router 폴더명을 수정하고 body에 blackMemberId를 추가했습니다 🥹 (죄송합니닷...)
https://github.com/user-attachments/assets/f289cec3-46e3-46f9-9ba8-b4bb7b49e8ec
-

feat: 특정 멤버 차단 api에 누락된 부분을 보충합니다.

---

app/notification/page.tsx
features/notification/components/organisms/notification-list-skeleton.tsx

- 알림 스켈레톤 디자인이 부자연스러워 보였습니다.
- 화면 크기에 따라 알맞게 width가 변화하도록 % 단위를 사용하였습니다.
- 화면 초기에 렌더링 되는 스켈레톤 item 개수를 조금 늘려주었습니다.
https://github.com/user-attachments/assets/b78c0d37-7636-43ff-9048-c7a5954da633
- NA

design: 알림 스켈레톤 디자인 수정

---

app/profile/[id]/page.tsx

- 차단한 계정 또는 차단된 계정의 경우 profileData가 없습니다.
- 계정이 없는 경우나 위와 같은 경우에는 NotFound를 띄워줍니다.
https://github.com/user-attachments/assets/8ae3188c-8e6a-49ff-b7ec-6955830b8b80
-

feat: 차단 당한 계정/차단한 계정일 경우 404 페이지로 이동합니다.

---

features/setting/components/organisms/step-3.tsx

- 사파리에서 탈퇴하기 버튼이 안 보입니다.
- vh -> dvh로 수정했습니다.
-
-

design: 탈퇴하기 화면에서 사파리 대응을 위해 높이 단위를 수정합니다.

---

features/profile/components/atoms/block-button.tsx

- 
- 스타일링을 추가합니다.
[as is] => [to be]
<div>
</div>
-

design: 차단 버튼 스타일링 추가합니다.

---

features/profile/hooks/use-block-dialog-handler.tsx

- 내가 A를 팔로우 한 후에 차단하면 팔로잉 수가 1 -> 0으로 수정되어야 하는데 수정이 되지 않습니다.
- 차단이 성공하면 나의 profileData를 refetch 합니다.
**[as is - ⚠️ 이 상태로 마이페이지에 가면 팔로잉 1로 남아 있습니다. ]**
https://github.com/user-attachments/assets/c840e284-f907-4e62-b498-95524159f239
**[to be]**
https://github.com/user-attachments/assets/bd8a753d-62b1-436b-8d4d-9313c6566a2d
- **위 상황은 내가 A를 팔로우 했다고 전제하고 있습니다.** 팔로우를 하지 않은 사람이라면 refetch가 비효율적으로 동작하기에 좀 더 고민해봐야 합니다.

feat: 차단 시 마이 페이지 refetch 합니다.

---

app/api/member/[blackMemberId]/black/route.ts
components/molecules/profile-list/profile-blocked-list-item.tsx
features/news/components/atoms/cheer-up-button.tsx
features/record-detail/sections/detail-diary.tsx
features/setting-blocked/apis/index.ts
features/setting-blocked/apis/use-unblocked.tsx
features/setting-blocked/index.ts

- 차단 헤제 api를 연동합니다
https://github.com/user-attachments/assets/95ada89e-aa14-4e5b-9536-7f4e334d99dd
- 기록 줄바꿈 처리 작업 / 소식 탭 응원 검증 api 수정건도 함께 올렸습니다!

feat: 차단 해제 api 연동

---

components/molecules/header-bar/header-back-button.tsx
components/molecules/menu/menu-item.tsx
features/main/components/calendar/atoms/view-image-button.tsx
features/record-detail/sections/detail-report-fab.tsx
features/record/components/atoms/delete-record-button.tsx
features/record/components/organisms/sub-info-section.tsx
features/setting/components/atom/list-item.tsx

- 누락된 cursor:pointer 스타일을 전체적으로 추가하였습니다.
- NA
- NA

chore: 누락된 cursor:pointer 스타일 추가

---

features/setting/components/organisms/setting-calendar.tsx

- 목표 거리를 설정할 때 사파리에서 스크롤이 발생합니다.
- vh 단위에서 dvh로 수정합니다.
-
-

fix: 사파리 대응으로 높이 단위 수정합니다.

---

app/setting/page.tsx

feat: update app version

---

app/api/apple/oauth/route.ts

feat: apple redirect 로직 추가

---

app/setting/page.tsx

- 앱 버전을 1.0.5로 수정하였습니다.
- NA
- NA

chore: 앱 버전 수정

---

README.md

-
- Readme 파일을 작성했습니다.
- NA
- NA

feat: Readme 파일을 작성합니다.

---

README.md
apis/fetch-data.ts
features/main/hooks/use-calendar-data.ts
features/notification/apis/use-count-notification.tsx

- api retry가 이루어지지 않았습니다.
- status error가 발생 할 때 error를 throw 해주었습니다.
https://github.com/user-attachments/assets/5ee0716f-288b-4c65-b7c2-37e9dab3a306
- NA

fix: fetch에서 에러 발생시 에러 던져주는 로직 추가

---

features/login/components/organisms/login-screen.tsx

- 로그인시 이용 동의 문구가 누락되었습니다.
- 앱 심사를 위해 문구를 추가하였습니다.
-

design: 로그인 버튼 아래 이용 동의 문구 추가

---

features/record-detail/components/date-picker.tsx
features/record-detail/sections/detail-description.tsx
features/record-detail/sections/detail-preview.tsx
features/record-detail/types/index.ts

- 기록 상세 페이지 QA 반영
- ~번째 기록 워딩 추가 / 날짜 영역 위치 변경
- lap > 바퀴 워딩 수정
- 심박수, 평균페이스, 칼로리 하나라도 있을 경우에만 돔 그리는 방식으로 변경
-
-

fix: QA 반영

---

features/record/utils/is-future.ts

- 주소로 직접 입력 했을 때의 미래 입력 방지 코드를 수정합니다.
- NA
- NA

fix: 미래 날짜 막는 버그 수정

---

features/record/components/organisms/lane-length-bottom-sheet.tsx

- 총 바퀴 수를 크게 입력 후, 레인 변경시 NaN이 발생했습니다.
- `,`로 인한 NaN 문제로 제거 후 다시 포매팅해주었습니다.
https://github.com/user-attachments/assets/755397c5-4ea8-474c-85bb-e67cf07b0cef
-

fix: 총바퀴 수가 커질 경우 레인 변경시 NaN 발생 문제 해결

---

app/analyzers/clarity.tsx
app/analyzers/index.ts
app/layout.tsx

chore: 분석 툴 clarity 추가

---

app/analyzers/clarity.tsx

- 비슷한 이슈가 존재하여 해당 이슈 코멘트들을 참고하여 수정하였습니다.
- https://github.com/microsoft/clarity/issues/247
- https://github.com/microsoft/clarity/issues/397
-
-

fix: 트래킹 툴 스크립트 Id 변경

---

app/analyzers/clarity.tsx
app/layout.tsx
package.json
pnpm-lock.yaml

-
- 디자인팀 요구사항인 GTM을 연결하였고, 추후 GA도 연결할 것 같아 미리 등록해두었습니다.
-
- 환경변수를 vercel에 등록해야해요!

chore: GA, GTM 연결

---

features/record/hooks/use-distance-page-modal.tsx

- 바퀴 수 tab을 default로 설정하였습니다. 
- NA

chore: 바퀴 수 tab을 default로 설정

---

components/atoms/waves/waves.tsx

- 크게 문제는 없지만, 올바르지 않은 path 명령으로 물결이 그려지고 있었습니다.
- 명령어를 용도에 맞게 수정하였습니다.
-
-

fix: 물결 컴포넌트 path 내부 명령어를 올바르게 수정
